# Generated by Django 6.0.6 on 2026-09-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishable_key', models.CharField(blank=True, max_length=255, verbose_name='Publishable key')),
                ('secret_key', models.CharField(blank=True, max_length=255, verbose_name='Secret key')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Webhook secret')),
            ],
            options={
                'verbose_name': 'Stripe Settings',
            },
        ),
    ]
