# Generated by Django 6.0.8 on 2026-10-05 19:35

import django.db.models.deletion
import taggit.managers
import wagtail_daisIE.pages
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('taxonomy', '0001_initial'),
        ('wagtail_daisIE', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarfeedtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_feed_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='dashboardpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='related',
            field=models.ManyToManyField(blank=True, to='core.glossaryterm'),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='related',
            field=models.ManyToManyField(blank=True, to='core.helparticle'),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='screenshots',
            field=models.ManyToManyField(blank=True, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='helparticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='core.helpcategory'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='localizationsettings',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='The admin-curated subset of languages offered to visitors.', related_name='+', to='taxonomy.language', verbose_name='Offered languages'),
        ),
        migrations.AddField(
            model_name='meetingdetailpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='meetingdetailpage',
            name='design_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Shared design page'),
        ),
        migrations.AddField(
            model_name='meetingdetailpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='meetingdetailpage',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Source model'),
        ),
        migrations.AddField(
            model_name='meetingindexpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='meetingindexpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='peerindexpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='peerindexpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='peerprofiledetailpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='peerprofiledetailpage',
            name='design_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Shared design page'),
        ),
        migrations.AddField(
            model_name='peerprofiledetailpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='peerprofiledetailpage',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Source model'),
        ),
        migrations.AddField(
            model_name='profileindexpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='profileindexpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='reviewdetailpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='reviewdetailpage',
            name='design_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Shared design page'),
        ),
        migrations.AddField(
            model_name='reviewdetailpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='reviewdetailpage',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Source model'),
        ),
        migrations.AddField(
            model_name='reviewindexpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='reviewindexpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='searchpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='settingspage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='userprofilepage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='userprofilepage',
            name='design_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Shared design page'),
        ),
        migrations.AddField(
            model_name='userprofilepage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='userprofilepage',
            name='source_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Source model'),
        ),
        migrations.AddConstraint(
            model_name='meetingdetailpage',
            constraint=models.UniqueConstraint(fields=('detail_key', 'source_content_type', 'source_object_id'), name='core_meetingdetailpage_unique_detail_source'),
        ),
        migrations.AddConstraint(
            model_name='peerprofiledetailpage',
            constraint=models.UniqueConstraint(fields=('detail_key', 'source_content_type', 'source_object_id'), name='core_peerprofiledetailpage_unique_detail_source'),
        ),
        migrations.AddConstraint(
            model_name='reviewdetailpage',
            constraint=models.UniqueConstraint(fields=('detail_key', 'source_content_type', 'source_object_id'), name='core_reviewdetailpage_unique_detail_source'),
        ),
        migrations.AddConstraint(
            model_name='userprofilepage',
            constraint=models.UniqueConstraint(fields=('detail_key', 'source_content_type', 'source_object_id'), name='core_userprofilepage_unique_detail_source'),
        ),
    ]
