# Generated by Django 5.2.4 on 2025-07-24 16:58

import django.core.validators
import django.db.models.deletion
import re
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=320)),
                ('description', models.TextField()),
                ('durations', models.CharField(help_text='These are durations (in minutes) that a session may be booked for', max_length=320, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Only digits allowed')])),
                ('is_published', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_provide_sessions', 'Can provide a session to support seekers'), ('can_view_sessions', 'Can view a session'), ('can_manage_sessions', 'Can manage all sessions')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=320)),
                ('description', models.TextField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.IntegerField(default=1, help_text='Number of people that can attend this session', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('is_published', models.BooleanField(default=False)),
                ('attendees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.session')),
            ],
            options={
                'permissions': [('can_provide_scheduled_events', 'Can provide a scheduled event to support seekers'), ('can_schedule_events', 'Can schedule an event'), ('can_manage_scheduled_events', 'Can manage all scheduled events')],
            },
        ),
        migrations.CreateModel(
            name='SessionAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='events.session')),
            ],
            options={
                'unique_together': {('session', 'starts_at')},
            },
        ),
    ]
