# Generated by Django 5.2.5 on 2025-08-15 02:15

from django.db import migrations, transaction

@transaction.atomic
def create_sessionsindexpage(apps, schema_editor):
    # Get models
    ContentType = apps.get_model("contenttypes.ContentType")
    Page = apps.get_model("wagtailcore.Page")
    SessionsIndexPage = apps.get_model("events.SessionsIndexPage")

    # Find homepage (first child of root)
    try:
        homepage = Page.objects.get(depth=2, path="00010001")
    except Page.DoesNotExist:
        raise RuntimeError("Homepage does not exist yet. Run homepage migration first.")

    # Delete the default sessions index page
    # If migration is run multiple times, it may have already been deleted
    Page.objects.filter(slug="sessions", depth=homepage.depth + 1, path__startswith=homepage.path).delete()

    # Calculate new child path: parent's path + next available 4-digit suffix
    children = Page.objects.filter(path__startswith=homepage.path, depth=homepage.depth + 1)
    if children.exists():
        last_child = children.order_by("-path").first()
        last_suffix = int(last_child.path[-4:])
        new_suffix = f"{last_suffix + 1:04d}"
    else:
        new_suffix = "0001"

    new_path = homepage.path + new_suffix

    # Create content type for SessionsIndexPage model
    sessionsindexpage_content_type, __ = ContentType.objects.get_or_create(
        model="sessionsindexpage", app_label="events"
    )

    # Create SessionsIndexPage as child of homepage (path auto-managed by wagtail)
    sessionsindex = SessionsIndexPage(
        title="Sessions",
        slug="sessions",
        path=new_path,
        depth=homepage.depth + 1,
        numchild=0,
        content_type=sessionsindexpage_content_type
    )
    sessionsindex.save()
    
    homepage.numchild = homepage.numchild + 1
    homepage.save()

@transaction.atomic
def remove_sessionsindexpage(apps, schema_editor):
    # Get models
    ContentType = apps.get_model("contenttypes.ContentType")
    SessionsIndexPage = apps.get_model("events.SessionsIndexPage")

    # Delete the default SessionsIndexPage
    SessionsIndexPage.objects.filter(slug="sessions", depth=2).delete()

    # Delete content type for sessionsindexpage model
    ContentType.objects.filter(model="sessionsindexpage", app_label="core").delete()


class Migration(migrations.Migration):
    run_before = [
        ("wagtailcore", "0053_locale_model"),
    ]

    dependencies = [
        ('core', '0002_create_homepage'),
        ('events', '0002_groupsessiondetailpage_peersessiondetailpage_and_more'),
    ]

    operations = [
        migrations.RunPython(create_sessionsindexpage, remove_sessionsindexpage),
    ]

