# Generated by Django 5.2.5 on 2025-08-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_groupsession_group_access_before_payment_price_zero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondetailpage',
            name='session_object_id',
            field=models.UUIDField(),
        ),
    ]
