# Generated by Django 5.2.5 on 2025-08-20 11:55

import datetime
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_groupsessionrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='peersessionavailability',
            name='occurrence',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Daily'), (1, 'Weekly'), (2, 'Monthly')], null=True),
        ),
        migrations.AlterField(
            model_name='peersessionrequest',
            name='attendee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_session_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='peersessionrequest',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='events.peersession'),
        ),
        migrations.AlterConstraint(
            model_name='peersessionrequest',
            name='peer_ends_at_gte_starts_at',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gte', django.db.models.expressions.CombinedExpression(models.F('starts_at'), '+', models.Value(datetime.timedelta(seconds=300))))), name='peer_ends_at_gte_starts_at', violation_error_message='Peer session must last at least 5 minutes'),
        ),
    ]
