# Generated by Django 5.2.5 on 2025-09-08 01:24

import datetime
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_groupsessionrequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='peersessionrequest',
            name='peer_ends_at_gte_starts_at',
        ),
        migrations.AddConstraint(
            model_name='peersessionrequest',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gte', django.db.models.expressions.CombinedExpression(models.F('starts_at'), '+', models.Value(datetime.timedelta(seconds=300))))), name='peer_request_ends_at_gte_starts_at', violation_error_message='Peer session must last at least 5 minutes'),
        ),
        migrations.AlterConstraint(
            model_name='groupsession',
            name='unique_published_group_session',
            constraint=models.UniqueConstraint(fields=('host', 'title', 'is_published'), name='unique_published_group_session', violation_error_message='Published sessions must be unique. Unpublish existing sessions with the same title or change the title of this session.'),
        ),
        migrations.AlterConstraint(
            model_name='groupsessionrequest',
            name='unique_group_request',
            constraint=models.UniqueConstraint(fields=('attendee', 'session'), name='unique_group_request', violation_error_message='Attendees may only request once per session.'),
        ),
        migrations.AlterConstraint(
            model_name='peersessionrequest',
            name='unique_peer_session_request',
            constraint=models.UniqueConstraint(fields=('attendee', 'session', 'starts_at'), name='unique_peer_session_request', violation_error_message='Attendees may only request once per session if an existing request starts at the same time.'),
        ),
    ]
