# Generated by Django 5.2.5 on 2025-08-20 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_peersessionavailability_occurrence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peersessionrequest',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='events.peersession'),
        ),
    ]
