# Generated by Django 5.2.5 on 2025-12-07 14:30

import apps.events.utils
import apps.events.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0006_remove_peersessionrequest_peer_ends_at_gte_starts_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="groupsession",
            name="language",
            field=models.CharField(
                choices=apps.events.utils.get_languages,
                default="en",
                help_text="This is the language that the session will be provided in",
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="peersession",
            name="languages",
            field=models.CharField(
                default='["en"]',
                help_text="These are languages that a session may be provided in",
                max_length=620,
                validators=[apps.events.validators.validate_language_codes],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="peersessionrequest",
            name="language",
            field=models.CharField(
                choices=apps.events.utils.get_languages,
                default="en",
                help_text="This is the language that the session will be provided in",
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
