# Generated by Django 5.2.5 on 2025-12-08 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_groupsession_language_peersession_languages_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publishable_key",
                    models.CharField(
                        blank=True,
                        help_text="Your organisation's Stripe API Publishable Key. This can be gotten from your Stripe dashboard. Starts with 'pk_'",
                        max_length=255,
                        null=True,
                        verbose_name="API Publishable Key",
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True,
                        help_text="Your organisation's Stripe API Secret Key. This can be gotten from your Stripe dashboard. Starts with 'sk_'",
                        max_length=255,
                        null=True,
                        verbose_name="API Secret Key",
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        blank=True,
                        help_text="Your organisation's Stripe Connect account ID. This can be gotten from your Stripe dashboard settings. Starts with 'acct_'",
                        max_length=255,
                        null=True,
                        verbose_name="Account ID",
                    ),
                ),
                (
                    "redirect_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL that you'd like users to be directed to after payments are made using Stripe's embedded elements",
                        null=True,
                        verbose_name="Redirect URL",
                    ),
                ),
                (
                    "application_fee",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The percentage of each payment that you'd like to take from users.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Application fee (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stripe API Settings",
            },
        ),
        migrations.CreateModel(
            name="WherebySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.TextField(
                        blank=True,
                        help_text="Your organisation's Whereby API key. This can be gotten from your Whereby dashboard.",
                        max_length=1024,
                        null=True,
                        verbose_name="API Key",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whereby API Settings",
            },
        ),
    ]
