# Generated by Django 5.2.5 on 2025-12-12 19:59

import django.core.validators
import django.db.models.deletion
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_stripesettings_wherebysettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filters",
                    wagtail.fields.StreamField(
                        [("group", 6)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Filter group label", "required": True},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Stable ID for this filter group (auto-generated if empty)",
                                    "required": False,
                                    "validators": [
                                        django.core.validators.RegexValidator(
                                            message="Slug can only contain letters, numbers, hyphens, and underscores.",
                                            regex="^[-a-zA-Z0-9_]+$",
                                        )
                                    ],
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Display label", "required": True},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Stable ID for this item (auto-generated if empty)",
                                    "required": False,
                                    "validators": [
                                        django.core.validators.RegexValidator(
                                            message="Slug can only contain letters, numbers, hyphens, and underscores.",
                                            regex="^[-a-zA-Z0-9_]+$",
                                        )
                                    ],
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 2), ("slug", 3)]],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.ListBlock",
                                (4,),
                                {"help_text": "Filter items"},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 0), ("slug", 1), ("items", 5)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Session filters",
            },
        ),
        migrations.CreateModel(
            name="GroupSessionReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PeerSessionReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="peerscheduledsessiongroupobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="peerscheduledsessiongroupobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="peerscheduledsessiongroupobjectpermission",
            name="group",
        ),
        migrations.RemoveField(
            model_name="peerscheduledsessiongroupobjectpermission",
            name="permission",
        ),
        migrations.AlterUniqueTogether(
            name="peerscheduledsessionuserobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="peerscheduledsessionuserobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="peerscheduledsessionuserobjectpermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="peerscheduledsessionuserobjectpermission",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="peersessionavailabilitygroupobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="peersessionavailabilitygroupobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="peersessionavailabilitygroupobjectpermission",
            name="group",
        ),
        migrations.RemoveField(
            model_name="peersessionavailabilitygroupobjectpermission",
            name="permission",
        ),
        migrations.AlterUniqueTogether(
            name="peersessionavailabilityuserobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="peersessionavailabilityuserobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="peersessionavailabilityuserobjectpermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="peersessionavailabilityuserobjectpermission",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="peersessionrequestgroupobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="peersessionrequestgroupobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="peersessionrequestgroupobjectpermission",
            name="group",
        ),
        migrations.RemoveField(
            model_name="peersessionrequestgroupobjectpermission",
            name="permission",
        ),
        migrations.AlterUniqueTogether(
            name="peersessionrequestuserobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="peersessionrequestuserobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="peersessionrequestuserobjectpermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="peersessionrequestuserobjectpermission",
            name="user",
        ),
        migrations.RemoveField(
            model_name="stripesettings",
            name="account_id",
        ),
        migrations.AddField(
            model_name="groupsession",
            name="allow_custom_price",
            field=models.BooleanField(
                default=False,
                help_text="Support seekers will be allowed to pay what they can.",
            ),
        ),
        migrations.AddField(
            model_name="groupsession",
            name="filters",
            field=models.JSONField(
                blank=True,
                help_text="These are filters applied for a session",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="groupsession",
            name="recurrence_ends_at",
            field=models.DateTimeField(
                blank=True, help_text="Leave blank for indefinite recurrence", null=True
            ),
        ),
        migrations.AddField(
            model_name="groupsession",
            name="recurrence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "Daily"),
                    (1, "Weekly"),
                    (2, "Every two weeks"),
                    (3, "Every three weeks"),
                    (4, "Monthly"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="groupsession",
            name="recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupsessionrequest",
            name="custom_price",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Cannot charge negative values"
                    ),
                    django.core.validators.MaxValueValidator(
                        9999999,
                        message="Cannot charge over 99,999 of a currency's unit. For higher values, try a different currency.",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="groupsessionrequest",
            name="meeting_link",
            field=models.URLField(
                blank=True,
                help_text="Video conference link for this session. Auto-generated via Whereby if not provided.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="peersession",
            name="allow_custom_price",
            field=models.BooleanField(
                default=False,
                help_text="Support seekers will be allowed to pay what they can.",
            ),
        ),
        migrations.AddField(
            model_name="peersession",
            name="filters",
            field=models.JSONField(
                blank=True,
                help_text="These are filters applied for a session",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="peersessionrequest",
            name="custom_price",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Cannot charge negative values"
                    ),
                    django.core.validators.MaxValueValidator(
                        9999999,
                        message="Cannot charge over 99,999 of a currency's unit. For higher values, try a different currency.",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="peersessionrequest",
            name="meeting_link",
            field=models.URLField(
                blank=True,
                help_text="Video conference link for this session. Auto-generated via Whereby if not provided.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sessionsindexpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("session_feed", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 10,
                            "help_text": "Maximum number of sessions to display (per page if paginated)",
                            "max_value": 50,
                            "min_value": 1,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("include_peer_sessions", 0),
                                ("include_group_sessions", 0),
                                ("show_filters", 1),
                                ("enable_pagination", 1),
                                ("limit", 2),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stripesettings",
            name="client_id",
            field=models.CharField(
                blank=True,
                help_text="Your organisation's Stripe Connect client ID. This can be gotten from your Stripe dashboard settings. Starts with 'ca_'",
                max_length=255,
                null=True,
                verbose_name="Client ID",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("recurrence_type__isnull", False), ("recurring", True)),
                    models.Q(("recurrence_type__isnull", True), ("recurring", False)),
                    _connector="OR",
                ),
                name="event_recurrence_type_required_if_recurring",
                violation_error_message="Events can occur repeatedly only if you set both recurring and recurrence type",
            ),
        ),
        migrations.AlterConstraint(
            model_name="groupsession",
            name="unique_published_group_session",
            constraint=models.UniqueConstraint(
                fields=("host", "title", "is_published"),
                name="unique_published_group_session",
                violation_error_message="Published sessions must be unique. Unpublish existing  sessions with the same title before publishing a new one.",
            ),
        ),
        migrations.AddField(
            model_name="groupsessionreview",
            name="attended_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="events.groupsession",
            ),
        ),
        migrations.AddField(
            model_name="groupsessionreview",
            name="attendee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_session_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="peersessionreview",
            name="attended_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="events.peersession",
            ),
        ),
        migrations.AddField(
            model_name="peersessionreview",
            name="attendee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peer_session_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="PeerScheduledSessionGroupObjectPermission",
        ),
        migrations.DeleteModel(
            name="PeerScheduledSessionUserObjectPermission",
        ),
        migrations.DeleteModel(
            name="PeerSessionAvailabilityGroupObjectPermission",
        ),
        migrations.DeleteModel(
            name="PeerSessionAvailabilityUserObjectPermission",
        ),
        migrations.DeleteModel(
            name="PeerSessionRequestGroupObjectPermission",
        ),
        migrations.DeleteModel(
            name="PeerSessionRequestUserObjectPermission",
        ),
        migrations.AddConstraint(
            model_name="groupsessionreview",
            constraint=models.UniqueConstraint(
                fields=("attended_session", "attendee"),
                name="unique_group_session_review",
                violation_error_message="You can only leave one review on each group session you've attended",
            ),
        ),
        migrations.AddConstraint(
            model_name="peersessionreview",
            constraint=models.UniqueConstraint(
                fields=("attended_session", "attendee"),
                name="unique_peer_session_review",
                violation_error_message="You can only leave one review on each peer session you've attended",
            ),
        ),
    ]
