# Generated by Django 5.2.5 on 2025-12-08 20:33

import django.core.validators
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_peersessionreview_groupsessionreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filters",
                    wagtail.fields.StreamField(
                        [("group", 6)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Filter group label", "required": True},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Stable ID for this filter group (auto-generated if empty)",
                                    "required": False,
                                    "validators": [
                                        django.core.validators.RegexValidator(
                                            message="Slug can only contain letters, numbers, hyphens, and underscores.",
                                            regex="^[-a-zA-Z0-9_]+$",
                                        )
                                    ],
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Display label", "required": True},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Stable ID for this item (auto-generated if empty)",
                                    "required": False,
                                    "validators": [
                                        django.core.validators.RegexValidator(
                                            message="Slug can only contain letters, numbers, hyphens, and underscores.",
                                            regex="^[-a-zA-Z0-9_]+$",
                                        )
                                    ],
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 2), ("slug", 3)]],
                                {},
                            ),
                            5: (
                                "wagtail.blocks.ListBlock",
                                (4,),
                                {"help_text": "Filter items"},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 0), ("slug", 1), ("items", 5)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Session filters",
            },
        ),
        migrations.AddField(
            model_name="groupsession",
            name="filters",
            field=models.JSONField(
                blank=True,
                help_text="These are filters applied for a session",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="peersession",
            name="filters",
            field=models.JSONField(
                blank=True,
                help_text="These are filters applied for a session",
                null=True,
            ),
        ),
    ]
