# Generated by Django 5.2.5 on 2025-12-08 18:37

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_peersessionreview_groupsessionreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filters",
                    wagtail.fields.StreamField(
                        [("lived_experience", 1), ("area_of_focus", 1)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.ListBlock", (0,), {}),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "Session filters",
            },
        ),
    ]
