# Generated by Django 6.0.2 on 2026-02-10 18:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_sessionsindexpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionsindexpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("session_feed", 5), ("peer_feed", 9)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Include peer sessions without availability",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Include group sessions at full capacity",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 10,
                            "help_text": "Maximum number of sessions to display (per page if paginated)",
                            "max_value": 50,
                            "min_value": 1,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("include_peer_sessions", 0),
                                ("include_group_sessions", 0),
                                ("include_unavailable", 1),
                                ("include_full_capacity", 2),
                                ("show_filters", 3),
                                ("enable_pagination", 3),
                                ("limit", 4),
                            ]
                        ],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Include peers with only unavailable sessions",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Include peers with only full-capacity group sessions",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 10,
                            "help_text": "Maximum number of peers to display (per page if paginated)",
                            "max_value": 50,
                            "min_value": 1,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("include_unavailable", 6),
                                ("include_full_capacity", 7),
                                ("show_filters", 3),
                                ("enable_pagination", 3),
                                ("limit", 8),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
