# Generated by Django 5.2.5 on 2025-12-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_filtersettings_groupsession_filters_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripesettings",
            name="account_id",
        ),
        migrations.AddField(
            model_name="stripesettings",
            name="client_id",
            field=models.CharField(
                blank=True,
                help_text="Your organisation's Stripe Connect client ID. This can be gotten from your Stripe dashboard settings. Starts with 'ca_'",
                max_length=255,
                null=True,
                verbose_name="Client ID",
            ),
        ),
    ]
