# Generated by Django 5.2.5 on 2025-12-09 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_remove_stripesettings_account_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="groupsession",
            name="recurrence_ends_at",
            field=models.DateTimeField(
                blank=True, help_text="Leave blank for indefinite recurrence", null=True
            ),
        ),
        migrations.AddField(
            model_name="groupsession",
            name="recurrence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (0, "Daily"),
                    (1, "Weekly"),
                    (2, "Every two weeks"),
                    (3, "Every three weeks"),
                    (4, "Monthly"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="groupsession",
            name="recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="groupsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("recurrence_type__isnull", False), ("recurring", True)),
                    models.Q(("recurrence_type__isnull", True), ("recurring", False)),
                    _connector="OR",
                ),
                name="event_recurrence_type_required_if_recurring",
                violation_error_message="Events can occur repeatedly only if you set both recurring and recurrence type",
            ),
        ),
    ]
