# Generated by Django 6.0.2 on 2026-02-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_alter_sessionsindexpage_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUploadSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "get_pronto_api_key",
                    models.CharField(
                        blank=True,
                        help_text="Your Get Pronto API key. This can be obtained from your Get Pronto dashboard.",
                        max_length=255,
                        null=True,
                        verbose_name="Get Pronto API Key",
                    ),
                ),
                (
                    "get_pronto_api_url",
                    models.URLField(
                        blank=True,
                        default="https://api.getpronto.com/v1/",
                        help_text="The base URL for the Get Pronto API. This is typically in the format 'https://api.getpronto.com/v1/'",
                        null=True,
                        verbose_name="Get Pronto API URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image Upload API Settings",
            },
        ),
    ]
