# Generated by Django 5.2.5 on 2025-12-09 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_groupsession_recurrence_ends_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupsession",
            name="allow_custom_price",
            field=models.BooleanField(
                default=False,
                help_text="Support seekers will be allowed to pay what they can.",
            ),
        ),
        migrations.AddField(
            model_name="groupsessionrequest",
            name="custom_price",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Cannot charge negative values"
                    ),
                    django.core.validators.MaxValueValidator(
                        9999999,
                        message="Cannot charge over 99,999 of a currency's unit. For higher values, try a different currency.",
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="peersession",
            name="allow_custom_price",
            field=models.BooleanField(
                default=False,
                help_text="Support seekers will be allowed to pay what they can.",
            ),
        ),
        migrations.AddField(
            model_name="peersessionrequest",
            name="custom_price",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Cannot charge negative values"
                    ),
                    django.core.validators.MaxValueValidator(
                        9999999,
                        message="Cannot charge over 99,999 of a currency's unit. For higher values, try a different currency.",
                    ),
                ],
            ),
        ),
    ]
