# Generated by Django 6.0.2 on 2026-02-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_imageuploadsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="peersessionrequest",
            name="accessibility_needs",
            field=models.TextField(
                blank=True,
                help_text="Let the host know about any accessibility needs you have so they can accommodate you",
                max_length=2048,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="imageuploadsettings",
            name="get_pronto_api_url",
            field=models.URLField(
                blank=True,
                default="https://api.getpronto.io/v1/",
                help_text="The base URL for the Get Pronto API. This is typically in the format 'https://api.getpronto.com/v1/'",
                null=True,
                verbose_name="Get Pronto API URL",
            ),
        ),
    ]
