# Generated by Django 5.2.5 on 2025-12-11 19:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_groupsession_allow_custom_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionsindexpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("session_feed", 3)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": True, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"default": False, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 10,
                            "help_text": "Maximum number of sessions to display (per page if paginated)",
                            "max_value": 50,
                            "min_value": 1,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("include_peer_sessions", 0),
                                ("include_group_sessions", 0),
                                ("show_filters", 1),
                                ("enable_pagination", 1),
                                ("limit", 2),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
