# Generated by Django 6.0.2 on 2026-02-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_add_accessibility_needs_to_peersessionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageuploadsettings",
            name="get_pronto_email",
            field=models.EmailField(
                blank=True,
                help_text="The email address associated with your Get Pronto account.",
                max_length=254,
                null=True,
                verbose_name="Get Pronto Email",
            ),
        ),
        migrations.AddField(
            model_name="imageuploadsettings",
            name="get_pronto_password",
            field=models.CharField(
                blank=True,
                help_text="The password for your Get Pronto account.",
                max_length=255,
                null=True,
                verbose_name="Get Pronto Password",
            ),
        ),
    ]
