# Generated by Django 6.0.2 on 2026-02-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_imageuploadsettings_get_pronto_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupsessionrequest",
            name="refund_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Approved"),
                    (1, "Rejected"),
                    (2, "Pending"),
                    (3, "Withdrawn"),
                ],
                default=0,
                help_text="Tracks whether a refund has been requested and its current state. Defaults to approved (no refund action pending).",
            ),
        ),
        migrations.AlterField(
            model_name="groupsessionrequest",
            name="refunded",
            field=models.BooleanField(
                default=False,
                help_text="\n                Payments will refunded if:\n                    (a) refunds are automatically approved and a user withdraws an approved request\n                    (b) a user requests a refund and the request is approved\n            ",
            ),
        ),
        migrations.AlterField(
            model_name="peersessionrequest",
            name="refund_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Approved"),
                    (1, "Rejected"),
                    (2, "Pending"),
                    (3, "Withdrawn"),
                ],
                default=0,
                help_text="Tracks whether a refund has been requested and its current state. Defaults to approved (no refund action pending).",
            ),
        ),
        migrations.AlterField(
            model_name="peersessionrequest",
            name="refunded",
            field=models.BooleanField(
                default=False,
                help_text="\n                Payments will refunded if:\n                    (a) refunds are automatically approved and a user withdraws an approved request\n                    (b) a user requests a refund and the request is approved\n            ",
            ),
        ),
    ]
