# Generated by Django 6.0.2 on 2026-03-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_fix_refund_defaults"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imageuploadsettings",
            options={"verbose_name": "Image Upload Settings"},
        ),
        migrations.RemoveField(
            model_name="imageuploadsettings",
            name="get_pronto_api_key",
        ),
        migrations.RemoveField(
            model_name="imageuploadsettings",
            name="get_pronto_api_url",
        ),
        migrations.RemoveField(
            model_name="imageuploadsettings",
            name="get_pronto_email",
        ),
        migrations.RemoveField(
            model_name="imageuploadsettings",
            name="get_pronto_password",
        ),
        migrations.AddField(
            model_name="imageuploadsettings",
            name="imagekit_private_key",
            field=models.CharField(
                blank=True,
                help_text="Your ImageKit Private Key. This can be obtained from your ImageKit dashboard.",
                max_length=255,
                null=True,
                verbose_name="ImageKit Private Key",
            ),
        ),
        migrations.AddField(
            model_name="imageuploadsettings",
            name="imagekit_public_key",
            field=models.CharField(
                blank=True,
                help_text="Your ImageKit Public Key. This can be obtained from your ImageKit dashboard.",
                max_length=255,
                null=True,
                verbose_name="ImageKit Public Key",
            ),
        ),
        migrations.AddField(
            model_name="imageuploadsettings",
            name="imagekit_url_endpoint",
            field=models.URLField(
                blank=True,
                help_text="Your ImageKit URL Endpoint. This can be obtained from your ImageKit dashboard.",
                null=True,
                verbose_name="ImageKit URL Endpoint",
            ),
        ),
    ]
