# Generated by Django 6.0.2 on 2026-03-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_alter_imageuploadsettings_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripesettings",
            name="redirect_url",
            field=models.CharField(
                blank=True,
                help_text="The URL that you'd like users to be directed to after payments are made using Stripe's embedded elements",
                max_length=255,
                null=True,
                verbose_name="Redirect URL",
            ),
        ),
    ]
