# Generated by Django 6.0.2 on 2026-04-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_alter_stripesettings_redirect_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageuploadsettings",
            name="get_pronto_api_key",
            field=models.CharField(
                blank=True,
                help_text="Your GetPronto API Key.",
                max_length=255,
                null=True,
                verbose_name="GetPronto API Key",
            ),
        ),
        migrations.AddField(
            model_name="imageuploadsettings",
            name="get_pronto_api_url",
            field=models.URLField(
                blank=True,
                help_text="GetPronto API base URL (e.g. https://api.getpronto.io/v1).",
                null=True,
                verbose_name="GetPronto API URL",
            ),
        ),
        migrations.AddField(
            model_name="imageuploadsettings",
            name="get_pronto_email",
            field=models.EmailField(
                blank=True,
                help_text="Email for GetPronto API authentication.",
                max_length=254,
                null=True,
                verbose_name="GetPronto Email",
            ),
        ),
        migrations.AddField(
            model_name="imageuploadsettings",
            name="get_pronto_password",
            field=models.CharField(
                blank=True,
                help_text="Password for GetPronto API authentication.",
                max_length=255,
                null=True,
                verbose_name="GetPronto Password",
            ),
        ),
        migrations.AddField(
            model_name="imageuploadsettings",
            name="image_provider",
            field=models.CharField(
                choices=[("imagekit", "ImageKit"), ("getpronto", "GetPronto")],
                default="imagekit",
                help_text="Select which image upload service to use.",
                max_length=20,
                verbose_name="Image Provider",
            ),
        ),
    ]
