# Generated by Django 5.2.5 on 2025-12-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accept_toc",
            field=models.BooleanField(default=False),
        ),
    ]
