# Generated by Django 5.2.5 on 2025-12-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_accept_toc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="display_picture",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_bio",
        ),
    ]
