# Generated by Django 5.2.5 on 2025-12-09 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_display_picture_remove_user_profile_bio"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="certificate",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "requested_session",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when you request a session",
                    ),
                ),
                (
                    "responded_session",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when a Care Provider has responded to your request",
                    ),
                ),
                (
                    "cancelled_session",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when your session is cancelled",
                    ),
                ),
                (
                    "session_reminders",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification before one (1) day and/or one (1) hour before your session starts",
                    ),
                ),
                (
                    "account_deleted",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when your account is deleted",
                    ),
                ),
                (
                    "payment_made",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when you make a payment",
                    ),
                ),
                (
                    "payment_refunded",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when your payment is refunded",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="notification_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PeerNotificationSettings",
            fields=[
                (
                    "requested_session",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when you request a session",
                    ),
                ),
                (
                    "responded_session",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when a Care Provider has responded to your request",
                    ),
                ),
                (
                    "cancelled_session",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when your session is cancelled",
                    ),
                ),
                (
                    "session_reminders",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification before one (1) day and/or one (1) hour before your session starts",
                    ),
                ),
                (
                    "account_deleted",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when your account is deleted",
                    ),
                ),
                (
                    "payment_made",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when you make a payment",
                    ),
                ),
                (
                    "published_session",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when you publish a session",
                    ),
                ),
                (
                    "host_session_requested",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when a Care Seeker requests a session from you",
                    ),
                ),
                (
                    "host_session_booked",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when you accept a request",
                    ),
                ),
                (
                    "host_session_cancelled",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when you or a Care Seeker cancel(s) a session",
                    ),
                ),
                (
                    "host_session_reminders",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification one (1) day and/or one (1) hour before a session provided by you starts",
                    ),
                ),
                (
                    "payment_received",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when you receive a payment",
                    ),
                ),
                (
                    "payment_refund_request",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when a Care Seeker requests a refund from you",
                    ),
                ),
                (
                    "payment_refunded",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "On this site"),
                            (2, "Via email"),
                            (3, "All"),
                        ],
                        help_text="You'll receive a notification when you refund a payment",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="peer_notification_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "display_picture",
                    models.ImageField(
                        blank=True,
                        help_text="This image will be displayed on a user's profile",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        blank=True,
                        help_text="This will be displayed on a user's profile as their summary",
                        null=True,
                    ),
                ),
                (
                    "access_needs",
                    models.TextField(
                        blank=True,
                        help_text="Care Providers will see this in your profile when you request a session",
                        max_length=10240,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StripeAccount",
            fields=[
                ("id", models.CharField(max_length=128, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stripe_account",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.IntegerField(
                        choices=[
                            (0, "Account"),
                            (1, "Payment"),
                            (2, "Session"),
                            (3, "Reminder"),
                        ]
                    ),
                ),
                ("body", models.TextField(max_length=10240)),
                ("read", models.BooleanField(default=False)),
                (
                    "sent_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CertificateGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.certificate",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("group", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="CertificateUserObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.certificate",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="NotificationSettingsGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.notificationsettings",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("group", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="NotificationSettingsUserObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.notificationsettings",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="PeerNotificationSettingsGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.peernotificationsettings",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("group", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="PeerNotificationSettingsUserObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.peernotificationsettings",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="ProfileGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("group", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="ProfileUserObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profile",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="StripeAccountGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.stripeaccount",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("group", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="StripeAccountUserObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.stripeaccount",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "permission", "content_object")},
            },
        ),
    ]
