# Generated by Django 5.2.5 on 2025-12-09 20:20

import apps.accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_certificate_notificationsettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(
                blank=True,
                choices=apps.accounts.utils.get_countries,
                help_text="Where you currently decide. This will be displayed on your profile and in searches.",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.TextField(
                blank=True,
                help_text="Enter a short description. This will be displayed on your profile.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="display_picture",
            field=models.ImageField(
                blank=True,
                help_text="This image will be displayed on your profile",
                null=True,
                upload_to="",
            ),
        ),
    ]
