# Generated by Django 6.0.2 on 2026-02-10 16:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_certificate_notificationsettings_peerfiltersettings_and_more",
        ),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeerPrivacySettings",
            fields=[
                (
                    "show_calendar",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, your availability calendar will be visible on your profile",
                    ),
                ),
                (
                    "show_peer_session_details",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, titles and timing of peer sessions will be shown on your calendar",
                    ),
                ),
                (
                    "show_group_session_details",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, non-sensitive details of group sessions will be shown on your calendar",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="peer_privacy_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="account_deleted",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when your account is deleted",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="cancelled_session",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when your session is cancelled",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="payment_made",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when you make a payment",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="payment_refunded",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when your payment is refunded",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="requested_session",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when you request a session",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="responded_session",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when a Care Provider has responded to your request",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="session_reminders",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification before one (1) day and/or one (1) hour before your session starts",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="peernotificationsettings",
            name="account_deleted",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when your account is deleted",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="peernotificationsettings",
            name="cancelled_session",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when your session is cancelled",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="peernotificationsettings",
            name="host_session_booked",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when you accept a request",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="peernotificationsettings",
            name="host_session_cancelled",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when you or a Care Seeker cancel(s) a session",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="peernotificationsettings",
            name="host_session_reminders",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification one (1) day and/or one (1) hour before a session provided by you starts",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="peernotificationsettings",
            name="host_session_requested",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when a Care Seeker requests a session from you",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="peernotificationsettings",
            name="payment_made",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when you make a payment",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="peernotificationsettings",
            name="payment_received",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when you receive a payment",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="peernotificationsettings",
            name="payment_refund_request",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when a Care Seeker requests a refund from you",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="peernotificationsettings",
            name="payment_refunded",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when you refund a payment",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="peernotificationsettings",
            name="published_session",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when you publish a session",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="peernotificationsettings",
            name="requested_session",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when you request a session",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="peernotificationsettings",
            name="responded_session",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification when a Care Provider has responded to your request",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="peernotificationsettings",
            name="session_reminders",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "None"),
                    (1, "On this site"),
                    (2, "Via email"),
                    (3, "All"),
                ],
                default=3,
                help_text="You'll receive a notification before one (1) day and/or one (1) hour before your session starts",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.CreateModel(
            name="PeerPrivacySettingsGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.peerprivacysettings",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("group", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="PeerPrivacySettingsUserObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.peerprivacysettings",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "permission", "content_object")},
            },
        ),
    ]
