# Generated by Django 6.0.2 on 2026-02-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_peer_privacy_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="display_picture",
        ),
        migrations.AddField(
            model_name="profile",
            name="display_picture_id",
            field=models.CharField(
                blank=True,
                help_text="GetPronto file ID for the profile picture",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="display_picture_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the profile picture hosted on GetPronto",
                max_length=1024,
                null=True,
            ),
        ),
    ]
