# Generated by Django 5.2.5 on 2025-12-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_peerfiltersettings_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="terms_and_conditions",
            field=models.TextField(
                blank=True,
                help_text="Care Seekers will see this before requesting a session",
                max_length=10240,
                null=True,
            ),
        ),
    ]
