# Generated by Django 6.0.2 on 2026-02-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_replace_display_picture_with_getpronto_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="link_url",
            field=models.CharField(
                blank=True,
                help_text="URL for the primary action associated with this notification",
                max_length=500,
                null=True,
            ),
        ),
    ]
