# Generated by Django 6.0.2 on 2026-03-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_add_link_url_to_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="display_picture_id",
            field=models.CharField(
                blank=True,
                help_text="ImageKit file ID for the profile picture",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="display_picture_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the profile picture hosted on ImageKit",
                max_length=1024,
                null=True,
            ),
        ),
    ]
