webservers:
  hosts:
    hetzner:
      ansible_host: "{{ lookup('ansible.builtin.env', 'HETZNER_SSH_HOST', default=undef()) }}"
      ansible_user: "{{ lookup('ansible.builtin.env', 'HETZNER_SSH_USER', default=undef()) }}"
      ansible_ssh_private_key_file: infra/inventory/ssh_key
