webservers:
  hosts:
    hetzner:
      ansible_host: "{{ lookup('ansible.builtin.env', 'HETZNER_SSH_HOST', default=undef()) }}"
      ansible_user: "{{ lookup('ansible.builtin.env', 'HETZNER_SSH_USER', default=undef()) }}"
      ansible_ssh_private_key_file: infra/inventory/ssh_key
  vars:
    ansible_ssh_public_key: "{{ lookup('ansible.builtin.env', 'HETZNER_SSH_PUBLIC_KEY', default=undef()) }}"
    django_port: 5000
    django_prometheus_port: 8001
    coolify_port: 8000
    gatus_port: 8080
    beszel_hub_port: 8090
    host_prometheus_port: 6060
    prometheus_port: 9090
    crowdsec_port: 9091
    coolify_api_url: "http://localhost:8000/api/v1"
    coolify_healthcheck_url: "http://localhost:8000/api/v1/health"
    coolify_admin_username: "{{ lookup('ansible.builtin.env', 'COOLIFY_ADMIN_USERNAME', default=undef()) }}"
    coolify_admin_email: "{{ lookup('ansible.builtin.env', 'COOLIFY_ADMIN_EMAIL', default=undef()) }}"
    coolify_admin_password: "{{ lookup('ansible.builtin.env', 'COOLIFY_ADMIN_PASSWORD', default=undef()) }}"
    coolify_admin_token: "{{ lookup('ansible.builtin.env', 'COOLIFY_ADMIN_TOKEN', default=undef()) }}"
    tailscale_oauth_client_secret: "{{ lookup('ansible.builtin.env', 'TS_OAUTH_CLIENT_SECRET', default=undef()) }}"
    tailscale_tag: "{{ lookup('ansible.builtin.env', 'TAILSCALE_TAG', default=undef()) }}"
