# Generated by Django 6.0.8 on 2026-10-05 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='ISO 3166-1 alpha-2 code')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['-sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Name')),
                ('name_local', models.CharField(max_length=256, unique=True, verbose_name='Local name')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='ISO 639-1 code')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Languages with higher sort order are displayed first.', verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['-sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Tag group',
                'verbose_name_plural': 'Tag groups',
                'ordering': ['-sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AllowedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='taxonomy.taggroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Allowed tag',
                'verbose_name_plural': 'Allowed tags',
                'ordering': ['group', '-sort_order', 'name'],
                'indexes': [models.Index(fields=['group', 'is_active'], name='taxonomy_tag_group_active_idx')],
            },
        ),
    ]
