# Generated by Django 6.0.6 on 2026-09-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Name')),
                ('name_local', models.CharField(max_length=256, unique=True, verbose_name='Local name')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='ISO 639-1 code')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Languages with higher sort order are displayed first.', verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['-sort_order', 'name'],
            },
        ),
    ]
