# Generated by Django 6.0.8 on 2026-10-05 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0003_2_11'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('kyc_completed', models.BooleanField(default=False, verbose_name='KYC completed')),
                ('stripe_connect_account_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_profile', to='djstripe.account', to_field='id')),
                ('stripe_customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_profile', to='djstripe.customer', to_field='id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
