# Generated by Django 6.0.2 on 2026-04-15 16:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0004_alter_contactformpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactformpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 22),
                    ("text", 25),
                    ("styled_text", 32),
                    ("text_image", 37),
                    ("cta", 42),
                    ("testimonial", 48),
                    ("features", 55),
                    ("faq", 60),
                    ("spacer", 62),
                    ("grid", 65),
                    ("marquee", 70),
                    ("blog_feed", 79),
                    ("back_button", 87),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "apps.core.blocks.ColorPickerBlock",
                        (),
                        {
                            "help_text": "Background color for the block",
                            "required": False,
                        },
                    ),
                    1: (
                        "apps.core.blocks.ColorPickerBlock",
                        (),
                        {"help_text": "Text color for the block", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("zigzag", "Zigzag"),
                                ("wave", "Wave"),
                                ("rounded", "Rounded"),
                                ("legoWave", "Lego Wave"),
                                ("leftCurve", "Left Curve"),
                                ("rightCurve", "Right Curve"),
                            ],
                            "help_text": "Border style",
                            "required": False,
                        },
                    ),
                    3: (
                        "apps.core.blocks.ColorPickerBlock",
                        (),
                        {"help_text": "Border color", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                            ],
                            "help_text": "Border size",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("style", 2), ("color", 3), ("size", 4)]],
                        {"help_text": "Top border configuration", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("style", 2), ("color", 3), ("size", 4)]],
                        {"help_text": "Bottom border configuration", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Show a back button at the top of this section",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Back",
                            "help_text": "Back button text",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Custom back link (leave blank for browser history)",
                            "required": False,
                        },
                    ),
                    10: (
                        "apps.core.blocks.ColorPickerBlock",
                        (),
                        {"help_text": "Back button text color", "required": False},
                    ),
                    11: (
                        "apps.core.blocks.ColorPickerBlock",
                        (),
                        {
                            "help_text": "Background color for buttons in the block",
                            "required": False,
                        },
                    ),
                    12: (
                        "apps.core.blocks.ColorPickerBlock",
                        (),
                        {
                            "help_text": "Text color for buttons in the block",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("heading", "Heading Font"),
                                ("subheading", "Subheading Font"),
                                ("body", "Body Font"),
                                ("custom", "Custom Font"),
                            ],
                            "help_text": "Select a root font or choose custom",
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Custom font-family value (only used when 'Custom' is selected)",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("font_type", 13), ("custom_font", 14)]],
                        {
                            "help_text": "Font for buttons in the block",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image for the hero",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading", "max_length": 255},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional subtitle or tagline",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text for the call-to-action button",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL for the button to link to",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("300px", "Small (300px)"),
                                ("500px", "Medium (500px)"),
                                ("800px", "Large (800px)"),
                            ],
                            "help_text": "Minimum height of the hero section",
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border", 5),
                                ("bottom_border", 6),
                                ("show_back_button", 7),
                                ("back_button_text", 8),
                                ("back_button_link", 9),
                                ("back_button_color", 10),
                                ("button_background_color", 11),
                                ("button_text_color", 12),
                                ("button_font", 15),
                                ("image", 16),
                                ("heading", 17),
                                ("subheading", 18),
                                ("button_text", 19),
                                ("button_link", 20),
                                ("min_height", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Main content"},
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("full", "Full Width"),
                                ("1200px", "1200px"),
                                ("900px", "900px"),
                            ]
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border", 5),
                                ("bottom_border", 6),
                                ("show_back_button", 7),
                                ("back_button_text", 8),
                                ("back_button_link", 9),
                                ("back_button_color", 10),
                                ("content", 23),
                                ("max_width", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "apps.core.blocks.ColorPickerBlock",
                        (),
                        {"help_text": "Default link color", "required": False},
                    ),
                    27: (
                        "apps.core.blocks.ColorPickerBlock",
                        (),
                        {
                            "help_text": "Link hover color (leave blank for default darkening)",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show underline on hover",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.DecimalBlock",
                        (),
                        {
                            "decimal_places": 2,
                            "help_text": "Hover opacity (0-1, leave blank for full opacity)",
                            "max_value": 1,
                            "min_value": 0,
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("0ms", "None"),
                                ("150ms", "Fast"),
                                ("300ms", "Normal"),
                                ("500ms", "Slow"),
                            ],
                            "help_text": "Transition duration for hover effects",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("hover_color", 27),
                                ("hover_underline", 28),
                                ("hover_opacity", 29),
                                ("transition_duration", 30),
                            ]
                        ],
                        {
                            "help_text": "Customize how links appear on hover",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border", 5),
                                ("bottom_border", 6),
                                ("show_back_button", 7),
                                ("back_button_text", 8),
                                ("back_button_link", 9),
                                ("back_button_color", 10),
                                ("content", 23),
                                ("link_color", 26),
                                ("link_hover_style", 31),
                                ("max_width", 24),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional section heading",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Content text"},
                    ),
                    35: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Side-by-side image"},
                    ),
                    36: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Image on Left"),
                                ("right", "Image on Right"),
                            ]
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border", 5),
                                ("bottom_border", 6),
                                ("show_back_button", 7),
                                ("back_button_text", 8),
                                ("back_button_link", 9),
                                ("back_button_color", 10),
                                ("heading", 33),
                                ("text", 34),
                                ("image", 35),
                                ("image_position", 36),
                            ]
                        ],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the CTA section", "max_length": 255},
                    ),
                    39: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional description text", "required": False},
                    ),
                    40: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text for the main button", "max_length": 100},
                    ),
                    41: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL for the button"},
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border", 5),
                                ("bottom_border", 6),
                                ("show_back_button", 7),
                                ("back_button_text", 8),
                                ("back_button_link", 9),
                                ("back_button_color", 10),
                                ("button_background_color", 11),
                                ("button_text_color", 12),
                                ("button_font", 15),
                                ("heading", 38),
                                ("description", 39),
                                ("button_text", 40),
                                ("button_link", 41),
                            ]
                        ],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "The testimonial text", "max_length": 1000},
                    ),
                    44: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Name of the person giving the testimonial",
                            "max_length": 255,
                        },
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title or role of the author (e.g., 'Peer Support Specialist')",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    46: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Author's profile image", "required": False},
                    ),
                    47: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Star rating (1-5)",
                            "max_value": 5,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border", 5),
                                ("bottom_border", 6),
                                ("show_back_button", 7),
                                ("back_button_text", 8),
                                ("back_button_link", 9),
                                ("back_button_color", 10),
                                ("quote", 43),
                                ("author_name", 44),
                                ("author_title", 45),
                                ("author_image", 46),
                                ("rating", 47),
                            ]
                        ],
                        {},
                    ),
                    49: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    50: ("wagtail.blocks.TextBlock", (), {"max_length": 500}),
                    51: (
                        "apps.core.blocks.EmojiChooserBlock",
                        (),
                        {
                            "help_text": "Optional icon for the feature",
                            "required": False,
                        },
                    ),
                    52: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 49), ("description", 50), ("icon", 51)]],
                        {},
                    ),
                    53: (
                        "wagtail.blocks.StreamBlock",
                        [[("feature", 52)]],
                        {"help_text": "Add up to 6 features", "max_num": 6},
                    ),
                    54: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("2", "2 columns"),
                                ("3", "3 columns"),
                                ("4", "4 columns"),
                            ]
                        },
                    ),
                    55: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border", 5),
                                ("bottom_border", 6),
                                ("show_back_button", 7),
                                ("back_button_text", 8),
                                ("back_button_link", 9),
                                ("back_button_color", 10),
                                ("heading", 33),
                                ("features", 53),
                                ("columns", 54),
                            ]
                        ],
                        {},
                    ),
                    56: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    57: ("wagtail.blocks.RichTextBlock", (), {}),
                    58: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 56), ("answer", 57)]],
                        {},
                    ),
                    59: (
                        "wagtail.blocks.StreamBlock",
                        [[("faq_item", 58)]],
                        {"help_text": "Add FAQ items"},
                    ),
                    60: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border", 5),
                                ("bottom_border", 6),
                                ("show_back_button", 7),
                                ("back_button_text", 8),
                                ("back_button_link", 9),
                                ("back_button_color", 10),
                                ("heading", 33),
                                ("items", 59),
                            ]
                        ],
                        {},
                    ),
                    61: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("20px", "Small"),
                                ("40px", "Medium"),
                                ("60px", "Large"),
                                ("100px", "Extra Large"),
                            ]
                        },
                    ),
                    62: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border", 5),
                                ("bottom_border", 6),
                                ("show_back_button", 7),
                                ("back_button_text", 8),
                                ("back_button_link", 9),
                                ("back_button_color", 10),
                                ("height", 61),
                            ]
                        ],
                        {},
                    ),
                    63: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("hero", 22),
                                ("text", 25),
                                ("text_image", 37),
                                ("cta", 42),
                                ("testimonial", 48),
                                ("features", 55),
                                ("faq", 60),
                                ("spacer", 62),
                            ]
                        ],
                        {},
                    ),
                    64: (
                        "wagtail.blocks.StreamBlock",
                        [[("grid_item", 63)]],
                        {"help_text": "Add items to the grid"},
                    ),
                    65: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border", 5),
                                ("bottom_border", 6),
                                ("show_back_button", 7),
                                ("back_button_text", 8),
                                ("back_button_link", 9),
                                ("back_button_color", 10),
                                ("items", 64),
                                ("columns", 54),
                            ]
                        ],
                        {},
                    ),
                    66: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to scroll in the marquee",
                            "max_length": 255,
                        },
                    ),
                    67: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": -1,
                            "help_text": "Number of times to repeat the marquee content. Set to -1 for infinite repetition.",
                            "max_value": 10,
                            "min_value": -1,
                        },
                    ),
                    68: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                            ]
                        },
                    ),
                    69: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("slow", "Slow"),
                                ("medium", "Medium"),
                                ("fast", "Fast"),
                            ]
                        },
                    ),
                    70: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border", 5),
                                ("bottom_border", 6),
                                ("show_back_button", 7),
                                ("back_button_text", 8),
                                ("back_button_link", 9),
                                ("back_button_color", 10),
                                ("content", 66),
                                ("repeat", 67),
                                ("size", 68),
                                ("speed", 69),
                            ]
                        ],
                        {},
                    ),
                    71: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Latest Posts",
                            "help_text": "Optional heading for the blog feed",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    72: (
                        "wagtail.blocks.StructBlock",
                        [[("font_type", 13), ("custom_font", 14)]],
                        {"help_text": "Font for the heading", "required": False},
                    ),
                    73: (
                        "apps.core.blocks.ColorPickerBlock",
                        (),
                        {"help_text": "Heading color", "required": False},
                    ),
                    74: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 10,
                            "help_text": "Maximum number of posts to display",
                            "max_value": 50,
                            "min_value": 1,
                        },
                    ),
                    75: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show post date",
                            "required": False,
                        },
                    ),
                    76: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show post excerpt/intro",
                            "required": False,
                        },
                    ),
                    77: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "No blog posts yet.",
                            "help_text": "Message to display when no posts are available",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    78: (
                        "apps.core.blocks.ColorPickerBlock",
                        (),
                        {
                            "help_text": "Link color for blog post titles",
                            "required": False,
                        },
                    ),
                    79: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border", 5),
                                ("bottom_border", 6),
                                ("show_back_button", 7),
                                ("back_button_text", 8),
                                ("back_button_link", 9),
                                ("back_button_color", 10),
                                ("heading", 71),
                                ("heading_font", 72),
                                ("heading_color", 73),
                                ("max_posts", 74),
                                ("show_date", 75),
                                ("show_excerpt", 76),
                                ("empty_message", 77),
                                ("link_color", 78),
                                ("link_hover_style", 31),
                            ]
                        ],
                        {},
                    ),
                    80: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Back",
                            "help_text": "Button text",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    81: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Custom link URL (leave blank to use browser history)",
                            "required": False,
                        },
                    ),
                    82: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Button position",
                        },
                    ),
                    83: (
                        "wagtail.blocks.StructBlock",
                        [[("font_type", 13), ("custom_font", 14)]],
                        {"help_text": "Button font", "required": False},
                    ),
                    84: (
                        "apps.core.blocks.ColorPickerBlock",
                        (),
                        {"help_text": "Button text color", "required": False},
                    ),
                    85: (
                        "apps.core.blocks.ColorPickerBlock",
                        (),
                        {"help_text": "Button background color", "required": False},
                    ),
                    86: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Show arrow icon",
                            "required": False,
                        },
                    ),
                    87: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border", 5),
                                ("bottom_border", 6),
                                ("show_back_button", 7),
                                ("back_button_text", 8),
                                ("back_button_link", 9),
                                ("back_button_color", 10),
                                ("text", 80),
                                ("link", 81),
                                ("position", 82),
                                ("font", 83),
                                ("button_text_color", 84),
                                ("button_background_color", 85),
                                ("show_icon", 86),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Optional content blocks above the contact form",
                null=True,
            ),
        ),
    ]
