# Update the system and install basic dependencies
---
- name: Update apt cache
  ansible.builtin.apt:
    upgrade: safe
    update_cache: true
    cache_valid_time: 3600

- name: Install base packages
  ansible.builtin.apt:
    name:
      - curl
      - git
      - openssh-server
      - fail2ban
      - jq
      - ufw
      - unzip
    state: present
    only_upgrade: true

- name: Add CrowdSec package repository
  ansible.builtin.shell: |
    curl -s https://install.crowdsec.net | sudo sh

- name: Install CrowdSec package
  ansible.builtin.apt:
    name:
      - crowdsec
      - crowdsec-firewall-bouncer-iptables
    state: present
    update_cache: true
