# Idempotently rename a file on a remote host.
#
# Parameters:
#   src - The source file path
#   dest - The destination file path
---
- name: Copy file to new name
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
  become: true

- name: Remove original
  ansible.builtin.file:
    path: "{{ item.src }}"
    state: absent
  become: true
