# Reusable handlers to restart services
---
- name: reload ufw
  community.general.ufw:
    state: reloaded

- name: restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: restart crowdsec
  ansible.builtin.systemd:
    name: crowdsec
    state: restarted
  become: true

- name: restart crowdsec-firewall-bouncer
  ansible.builtin.systemd:
    name: crowdsec-firewall-bouncer
    state: restarted
  become: true
