# Generated by Django 5.2.4 on 2025-07-25 20:25

from django.db import migrations
from ..utils import create_groups, delete_groups


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_homepage'),
    ]

    operations = [migrations.RunPython(create_groups, delete_groups)]
