# Generated by Django 5.2.5 on 2025-12-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_homepage_body_homepage_hero_cta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.URLField(
                        help_text="Your organisation's terms and conditions URL"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
