# Generated by Django 5.2.5 on 2025-12-12 16:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="hero_cta",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_cta_link",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="hero_text",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="image",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="body",
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 8),
                    ("text", 12),
                    ("text_image", 17),
                    ("cta", 25),
                    ("testimonial", 31),
                    ("features", 39),
                    ("faq", 44),
                    ("spacer", 46),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image for the hero",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading", "max_length": 255},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional subtitle or tagline",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text for the call-to-action button",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL for the button to link to",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("blue", "Blue"),
                                ("navy", "Navy Blue"),
                                ("gray", "Light Gray"),
                                ("black", "Black"),
                            ],
                            "help_text": "Background color for the hero section",
                        },
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("black", "Black"),
                                ("blue", "Blue"),
                                ("gray", "Dark Gray"),
                            ],
                            "help_text": "Text color for heading and subheading",
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("300px", "Small (300px)"),
                                ("500px", "Medium (500px)"),
                                ("800px", "Large (800px)"),
                            ],
                            "help_text": "Minimum height of the hero section",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 0),
                                ("heading", 1),
                                ("subheading", 2),
                                ("button_text", 3),
                                ("button_link", 4),
                                ("background_color", 5),
                                ("text_color", 6),
                                ("min_height", 7),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h1",
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                                "code",
                                "blockquote",
                            ],
                            "help_text": "Main content",
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("light-gray", "Light Gray"),
                                ("blue-light", "Light Blue"),
                            ],
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("full", "Full Width"),
                                ("1200px", "1200px"),
                                ("900px", "900px"),
                            ]
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("content", 9), ("background_color", 10), ("max_width", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional section heading",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "blockquote",
                            ],
                            "help_text": "Content text",
                        },
                    ),
                    15: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Side-by-side image"},
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Image on Left"),
                                ("right", "Image on Right"),
                            ]
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("text", 14),
                                ("image", 15),
                                ("image_position", 16),
                                ("background_color", 10),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the CTA section", "max_length": 255},
                    ),
                    19: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional description text", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text for the main button", "max_length": 100},
                    ),
                    21: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL for the button"},
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary (Blue)"),
                                ("secondary", "Secondary (Gray)"),
                                ("success", "Success (Green)"),
                            ]
                        },
                    ),
                    23: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("navy", "Navy Blue"),
                                ("light-gray", "Light Gray"),
                            ]
                        },
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("black", "Black"),
                                ("blue", "Blue"),
                            ]
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 18),
                                ("description", 19),
                                ("button_text", 20),
                                ("button_link", 21),
                                ("button_style", 22),
                                ("background_color", 23),
                                ("text_color", 24),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "The testimonial text", "max_length": 1000},
                    ),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Name of the person giving the testimonial",
                            "max_length": 255,
                        },
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title or role of the author (e.g., 'Peer Support Specialist')",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Author's profile image", "required": False},
                    ),
                    30: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Star rating (1-5)",
                            "max_value": 5,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("quote", 26),
                                ("author_name", 27),
                                ("author_title", 28),
                                ("author_image", 29),
                                ("rating", 30),
                            ]
                        ],
                        {},
                    ),
                    32: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    33: ("wagtail.blocks.TextBlock", (), {"max_length": 500}),
                    34: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("heart", "Heart"),
                                ("users", "Users"),
                                ("lock", "Lock"),
                                ("bell", "Bell"),
                                ("checkmark", "Checkmark"),
                                ("star", "Star"),
                            ]
                        },
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 32), ("description", 33), ("icon", 34)]],
                        {},
                    ),
                    36: (
                        "wagtail.blocks.StreamBlock",
                        [[("feature", 35)]],
                        {"help_text": "Add up to 6 features", "max_num": 6},
                    ),
                    37: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("2", "2 columns"),
                                ("3", "3 columns"),
                                ("4", "4 columns"),
                            ]
                        },
                    ),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("white", "White"),
                                ("light-gray", "Light Gray"),
                            ],
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("heading", 13),
                                ("features", 36),
                                ("columns", 37),
                                ("background_color", 38),
                            ]
                        ],
                        {},
                    ),
                    40: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    41: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul"]},
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 40), ("answer", 41)]],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.StreamBlock",
                        [[("faq_item", 42)]],
                        {"help_text": "Add FAQ items"},
                    ),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 13), ("items", 43)]],
                        {},
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("20px", "Small"),
                                ("40px", "Medium"),
                                ("60px", "Large"),
                                ("100px", "Extra Large"),
                            ]
                        },
                    ),
                    46: ("wagtail.blocks.StructBlock", [[("height", 45)]], {}),
                },
                help_text="Build your page by adding blocks",
                null=True,
            ),
        ),
    ]
