# Generated by Django 5.2.5 on 2025-12-12 19:59

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_homepage_hero_cta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplateSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_created_greeting",
                    wagtail.fields.RichTextField(
                        default="Your account has been created successfully. Welcome to our community!",
                        help_text="Greeting text for account creation notification",
                    ),
                ),
                (
                    "account_created_body",
                    wagtail.fields.RichTextField(
                        default="Start by exploring sessions, connecting with peers, or setting up your profile. If you have any questions, our support team is here to help.",
                        help_text="Main body text for account creation notification",
                    ),
                ),
                (
                    "account_closed_greeting",
                    wagtail.fields.RichTextField(
                        default="We're sorry to see you go. Your account has been closed as requested.",
                        help_text="Greeting text for account closure notification",
                    ),
                ),
                (
                    "account_closed_body",
                    wagtail.fields.RichTextField(
                        default="If you have any questions about your account closure or need to retrieve any information, please contact our support team within 30 days of this notice.",
                        help_text="Main body text for account closure notification",
                    ),
                ),
                (
                    "account_closed_note",
                    wagtail.fields.RichTextField(
                        default="We hope to see you in the community again someday!",
                        help_text="Closing note for account closure notification",
                    ),
                ),
                (
                    "group_upgrade_greeting",
                    wagtail.fields.RichTextField(
                        default="Congratulations! You've been upgraded to a Peer in the Neuromancers community.",
                        help_text="Greeting text when user is upgraded to Peer",
                    ),
                ),
                (
                    "group_upgrade_body",
                    wagtail.fields.RichTextField(
                        default="As a Peer, you can now create sessions and share your expertise with support seekers. Complete your profile and set up your session offerings to get started.",
                        help_text="Main body text for Peer upgrade notification",
                    ),
                ),
                (
                    "group_downgrade_greeting",
                    wagtail.fields.RichTextField(
                        default="Your account role has been updated.",
                        help_text="Greeting text when user role changes (general)",
                    ),
                ),
                (
                    "group_downgrade_body",
                    wagtail.fields.RichTextField(
                        default="Your role has been updated in our community. Please review your account settings to see what features are available to you.",
                        help_text="Main body text for general role change notification",
                    ),
                ),
                (
                    "session_published_greeting",
                    wagtail.fields.RichTextField(
                        default="Congratulations! Your session has been published.",
                        help_text="Greeting text for session published notification (shown to host)",
                    ),
                ),
                (
                    "session_published_body",
                    wagtail.fields.RichTextField(
                        default="Your session is now visible to support seekers. Support seekers can now request sessions with you. Check your notifications regularly for new requests.",
                        help_text="Main body text for session published notification",
                    ),
                ),
                (
                    "session_requested_greeting",
                    wagtail.fields.RichTextField(
                        default="A support seeker has requested to book your session.",
                        help_text="Greeting text for session request notification (shown to host)",
                    ),
                ),
                (
                    "session_requested_body",
                    wagtail.fields.RichTextField(
                        default="Review this request and either approve or decline it.",
                        help_text="Main body text for session request notification",
                    ),
                ),
                (
                    "session_approved_greeting",
                    wagtail.fields.RichTextField(
                        default="Great news! Your request has been approved.",
                        help_text="Greeting text for session approval notification (shown to seeker)",
                    ),
                ),
                (
                    "session_approved_body",
                    wagtail.fields.RichTextField(
                        default="Your session is now confirmed. Please arrive a few minutes early. If you have any questions, reach out to your host.",
                        help_text="Main body text for session approval notification",
                    ),
                ),
                (
                    "payment_made_greeting",
                    wagtail.fields.RichTextField(
                        default="Thank you for your payment! Your session is now confirmed.",
                        help_text="Greeting text for payment confirmation (shown to seeker)",
                    ),
                ),
                (
                    "payment_made_body",
                    wagtail.fields.RichTextField(
                        default="Your payment has been securely processed through Stripe. You'll receive a separate confirmation email from Stripe with your receipt.",
                        help_text="Main body text for payment confirmation",
                    ),
                ),
                (
                    "payment_received_greeting",
                    wagtail.fields.RichTextField(
                        default="You've received a payment for your session!",
                        help_text="Greeting text for payment received notification (shown to host)",
                    ),
                ),
                (
                    "payment_received_body",
                    wagtail.fields.RichTextField(
                        default="The payment has been processed and transferred to your connected Stripe account. You can view your payment history and balance in your account dashboard.",
                        help_text="Main body text for payment received notification",
                    ),
                ),
                (
                    "refund_requested_greeting",
                    wagtail.fields.RichTextField(
                        default="A support seeker has requested a refund for their session payment.",
                        help_text="Greeting text for refund request notification (shown to host)",
                    ),
                ),
                (
                    "refund_requested_body",
                    wagtail.fields.RichTextField(
                        default="Please review this request and decide whether to approve or decline the refund. You can manage this in your account.",
                        help_text="Main body text for refund request notification",
                    ),
                ),
                (
                    "refund_requested_note",
                    wagtail.fields.RichTextField(
                        default="Note: You're not required to approve this refund, but doing so helps maintain a positive experience for support seekers.",
                        help_text="Note text shown at end of refund request notification",
                    ),
                ),
                (
                    "refund_approved_greeting",
                    wagtail.fields.RichTextField(
                        default="Good news! Your refund request has been approved.",
                        help_text="Greeting text for refund approval notification (shown to seeker)",
                    ),
                ),
                (
                    "refund_approved_body",
                    wagtail.fields.RichTextField(
                        default="We appreciate your understanding. If you have any feedback about your experience, we'd love to hear from you.",
                        help_text="Main body text for refund approval notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Templates",
            },
        ),
    ]
