# Generated by Django 6.0.2 on 2026-02-10 16:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 14),
                    ("text", 17),
                    ("text_image", 22),
                    ("cta", 27),
                    ("testimonial", 33),
                    ("features", 40),
                    ("faq", 45),
                    ("spacer", 47),
                    ("grid", 50),
                    ("marquee", 54),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("transparent", "Transparent"),
                                ("white", "White"),
                                ("black", "Black"),
                                ("safeLightAccent", "Safe Light Accent"),
                                ("safeDarkAccent", "Safe Dark Accent"),
                                ("safeInverseAccent", "Safe Inverse Accent"),
                                ("safeInverseLightAccent", "Safe Inverse Light Accent"),
                                ("safeInverseDarkAccent", "Safe Inverse Dark Accent"),
                                ("accent", "Accent"),
                                ("lightAccent", "Light Accent"),
                                ("darkAccent", "Dark Accent"),
                            ],
                            "help_text": "Background color for the block",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("transparent", "Transparent"),
                                ("white", "White"),
                                ("black", "Black"),
                                ("safeLightAccent", "Safe Light Accent"),
                                ("safeDarkAccent", "Safe Dark Accent"),
                                ("safeInverseAccent", "Safe Inverse Accent"),
                                ("safeInverseLightAccent", "Safe Inverse Light Accent"),
                                ("safeInverseDarkAccent", "Safe Inverse Dark Accent"),
                                ("accent", "Accent"),
                                ("lightAccent", "Light Accent"),
                                ("darkAccent", "Dark Accent"),
                            ],
                            "help_text": "Text color for the block",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("zigzag", "Zigzag"),
                                ("wave", "Wave"),
                                ("rounded", "Rounded"),
                                ("legoWave", "Lego Wave"),
                                ("leftCurve", "Left Curve"),
                                ("rightCurve", "Right Curve"),
                            ],
                            "help_text": "Top border style for the block",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("transparent", "Transparent"),
                                ("white", "White"),
                                ("black", "Black"),
                                ("safeLightAccent", "Safe Light Accent"),
                                ("safeDarkAccent", "Safe Dark Accent"),
                                ("safeInverseAccent", "Safe Inverse Accent"),
                                ("safeInverseLightAccent", "Safe Inverse Light Accent"),
                                ("safeInverseDarkAccent", "Safe Inverse Dark Accent"),
                                ("accent", "Accent"),
                                ("lightAccent", "Light Accent"),
                                ("darkAccent", "Dark Accent"),
                            ],
                            "help_text": "Top border color for the block",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("none", "None"),
                                ("zigzag", "Zigzag"),
                                ("wave", "Wave"),
                                ("rounded", "Rounded"),
                                ("legoWave", "Lego Wave"),
                                ("leftCurve", "Left Curve"),
                                ("rightCurve", "Right Curve"),
                            ],
                            "help_text": "Bottom border style for the block",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("transparent", "Transparent"),
                                ("white", "White"),
                                ("black", "Black"),
                                ("safeLightAccent", "Safe Light Accent"),
                                ("safeDarkAccent", "Safe Dark Accent"),
                                ("safeInverseAccent", "Safe Inverse Accent"),
                                ("safeInverseLightAccent", "Safe Inverse Light Accent"),
                                ("safeInverseDarkAccent", "Safe Inverse Dark Accent"),
                                ("accent", "Accent"),
                                ("lightAccent", "Light Accent"),
                                ("darkAccent", "Dark Accent"),
                            ],
                            "help_text": "Bottom border color for the block",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("transparent", "Transparent"),
                                ("white", "White"),
                                ("black", "Black"),
                                ("safeLightAccent", "Safe Light Accent"),
                                ("safeDarkAccent", "Safe Dark Accent"),
                                ("safeInverseAccent", "Safe Inverse Accent"),
                                ("safeInverseLightAccent", "Safe Inverse Light Accent"),
                                ("safeInverseDarkAccent", "Safe Inverse Dark Accent"),
                                ("accent", "Accent"),
                                ("lightAccent", "Light Accent"),
                                ("darkAccent", "Dark Accent"),
                            ],
                            "help_text": "Background color for buttons in the block",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("transparent", "Transparent"),
                                ("white", "White"),
                                ("black", "Black"),
                                ("safeLightAccent", "Safe Light Accent"),
                                ("safeDarkAccent", "Safe Dark Accent"),
                                ("safeInverseAccent", "Safe Inverse Accent"),
                                ("safeInverseLightAccent", "Safe Inverse Light Accent"),
                                ("safeInverseDarkAccent", "Safe Inverse Dark Accent"),
                                ("accent", "Accent"),
                                ("lightAccent", "Light Accent"),
                                ("darkAccent", "Dark Accent"),
                            ],
                            "help_text": "Text color for buttons in the block",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Background image for the hero",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Main heading", "max_length": 255},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional subtitle or tagline",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text for the call-to-action button",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "URL for the button to link to",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("300px", "Small (300px)"),
                                ("500px", "Medium (500px)"),
                                ("800px", "Large (800px)"),
                            ],
                            "help_text": "Minimum height of the hero section",
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border_style", 2),
                                ("top_border_color", 3),
                                ("bottom_border_style", 4),
                                ("bottom_border_color", 5),
                                ("button_background_color", 6),
                                ("button_text_color", 7),
                                ("image", 8),
                                ("heading", 9),
                                ("subheading", 10),
                                ("button_text", 11),
                                ("button_link", 12),
                                ("min_height", 13),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h1",
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "hr",
                                "code",
                                "blockquote",
                            ],
                            "help_text": "Main content",
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("full", "Full Width"),
                                ("1200px", "1200px"),
                                ("900px", "900px"),
                            ]
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border_style", 2),
                                ("top_border_color", 3),
                                ("bottom_border_style", 4),
                                ("bottom_border_color", 5),
                                ("content", 15),
                                ("max_width", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional section heading",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "blockquote",
                            ],
                            "help_text": "Content text",
                        },
                    ),
                    20: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Side-by-side image"},
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Image on Left"),
                                ("right", "Image on Right"),
                            ]
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border_style", 2),
                                ("top_border_color", 3),
                                ("bottom_border_style", 4),
                                ("bottom_border_color", 5),
                                ("heading", 18),
                                ("text", 19),
                                ("image", 20),
                                ("image_position", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Heading for the CTA section", "max_length": 255},
                    ),
                    24: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Optional description text", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text for the main button", "max_length": 100},
                    ),
                    26: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"help_text": "URL for the button"},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border_style", 2),
                                ("top_border_color", 3),
                                ("bottom_border_style", 4),
                                ("bottom_border_color", 5),
                                ("button_background_color", 6),
                                ("button_text_color", 7),
                                ("heading", 23),
                                ("description", 24),
                                ("button_text", 25),
                                ("button_link", 26),
                            ]
                        ],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "The testimonial text", "max_length": 1000},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Name of the person giving the testimonial",
                            "max_length": 255,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Title or role of the author (e.g., 'Peer Support Specialist')",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"help_text": "Author's profile image", "required": False},
                    ),
                    32: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Star rating (1-5)",
                            "max_value": 5,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border_style", 2),
                                ("top_border_color", 3),
                                ("bottom_border_style", 4),
                                ("bottom_border_color", 5),
                                ("quote", 28),
                                ("author_name", 29),
                                ("author_title", 30),
                                ("author_image", 31),
                                ("rating", 32),
                            ]
                        ],
                        {},
                    ),
                    34: ("wagtail.blocks.CharBlock", (), {"max_length": 100}),
                    35: ("wagtail.blocks.TextBlock", (), {"max_length": 500}),
                    36: (
                        "apps.core.custom_blocks.EmojiChooserBlock",
                        (),
                        {
                            "help_text": "Optional icon for the feature",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 34), ("description", 35), ("icon", 36)]],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.StreamBlock",
                        [[("feature", 37)]],
                        {"help_text": "Add up to 6 features", "max_num": 6},
                    ),
                    39: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("2", "2 columns"),
                                ("3", "3 columns"),
                                ("4", "4 columns"),
                            ]
                        },
                    ),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border_style", 2),
                                ("top_border_color", 3),
                                ("bottom_border_style", 4),
                                ("bottom_border_color", 5),
                                ("heading", 18),
                                ("features", 38),
                                ("columns", 39),
                            ]
                        ],
                        {},
                    ),
                    41: ("wagtail.blocks.CharBlock", (), {"max_length": 255}),
                    42: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link", "ol", "ul"]},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 41), ("answer", 42)]],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.StreamBlock",
                        [[("faq_item", 43)]],
                        {"help_text": "Add FAQ items"},
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border_style", 2),
                                ("top_border_color", 3),
                                ("bottom_border_style", 4),
                                ("bottom_border_color", 5),
                                ("heading", 18),
                                ("items", 44),
                            ]
                        ],
                        {},
                    ),
                    46: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("20px", "Small"),
                                ("40px", "Medium"),
                                ("60px", "Large"),
                                ("100px", "Extra Large"),
                            ]
                        },
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border_style", 2),
                                ("top_border_color", 3),
                                ("bottom_border_style", 4),
                                ("bottom_border_color", 5),
                                ("height", 46),
                            ]
                        ],
                        {},
                    ),
                    48: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("hero", 14),
                                ("text", 17),
                                ("text_image", 22),
                                ("cta", 27),
                                ("testimonial", 33),
                                ("features", 40),
                                ("faq", 45),
                                ("spacer", 47),
                            ]
                        ],
                        {},
                    ),
                    49: (
                        "wagtail.blocks.StreamBlock",
                        [[("grid_item", 48)]],
                        {"help_text": "Add items to the grid"},
                    ),
                    50: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border_style", 2),
                                ("top_border_color", 3),
                                ("bottom_border_style", 4),
                                ("bottom_border_color", 5),
                                ("items", 49),
                                ("columns", 39),
                            ]
                        ],
                        {},
                    ),
                    51: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to scroll in the marquee",
                            "max_length": 255,
                        },
                    ),
                    52: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("small", "Small"),
                                ("medium", "Medium"),
                                ("large", "Large"),
                            ]
                        },
                    ),
                    53: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("slow", "Slow"),
                                ("medium", "Medium"),
                                ("fast", "Fast"),
                            ]
                        },
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_color", 0),
                                ("text_color", 1),
                                ("top_border_style", 2),
                                ("top_border_color", 3),
                                ("bottom_border_style", 4),
                                ("bottom_border_color", 5),
                                ("content", 51),
                                ("size", 52),
                                ("speed", 53),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Build your page by adding blocks",
                null=True,
            ),
        ),
    ]
