# Generated by Django 6.0.6 on 2026-09-08 18:18

import django.core.validators
import django.db.models.deletion
import django_fsm
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], max_length=10, verbose_name='Frequency')),
                ('interval', models.PositiveIntegerField(default=1, help_text='How often the meeting repeats (e.g. every 2 weeks).', verbose_name='Interval')),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='List of ISO day numbers (1=Mon .. 7=Sun) for weekly/biweekly recurrences. Ignored for daily recurrences.', verbose_name='Days of week')),
                ('end_date', models.DateField(blank=True, help_text='The recurrence stops on this date. Leave blank for no end.', null=True, verbose_name='End date')),
                ('max_occurrences', models.PositiveIntegerField(blank=True, help_text='Maximum number of occurrences. Leave blank for unlimited (until end_date).', null=True, verbose_name='Max occurrences')),
            ],
            options={
                'verbose_name': 'Recurrence rule',
                'verbose_name_plural': 'Recurrence rules',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('terms', models.TextField(blank=True, help_text='Free-text terms and conditions.', verbose_name='Terms')),
                ('meeting_type', models.CharField(choices=[('1:1', '1:1'), ('group', 'Group')], max_length=10, verbose_name='Meeting type')),
                ('meeting_link', models.URLField(blank=True, help_text='Auto-populated with a Whereby meeting link close to the time of the event if left empty. Only valid for group meetings.', verbose_name='Meeting link')),
                ('whereby_meeting_id', models.CharField(blank=True, max_length=255, verbose_name='Whereby meeting ID')),
                ('pricing_type', models.CharField(choices=[('per_hour', 'Per hour'), ('fixed', 'Fixed price'), ('sliding_scale', 'Sliding scale')], max_length=20, verbose_name='Pricing type')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('sliding_scale_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sliding scale min')),
                ('sliding_scale_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sliding scale max')),
                ('currency', models.CharField(default='GBP', max_length=3, verbose_name='Currency')),
                ('approval_policy', models.CharField(choices=[('approval_required', 'Approval required'), ('pay_before_join', 'Pay before join'), ('pay_after_join', 'Pay after join')], max_length=20, verbose_name='Approval policy')),
                ('refund_requires_approval', models.BooleanField(default=True, verbose_name='Refund requires approval')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants. Required for group meetings, up to 200.', null=True, validators=[django.core.validators.MaxValueValidator(200)], verbose_name='Max participants')),
                ('status', django_fsm.FSMField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=50, protected=True, verbose_name='Status')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled at')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='Duration (minutes)')),
                ('languages', models.ManyToManyField(blank=True, related_name='meetings', to='taxonomy.language')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('recurrence_rule', models.ForeignKey(blank=True, help_text='Recurrence rule for group meetings. Not applicable to 1:1 meetings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='meetings.recurrencerule')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', django_fsm.FSMField(choices=[('pending_approval', 'Pending approval'), ('pending_payment', 'Pending payment'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=50, protected=True, verbose_name='Status')),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price paid')),
                ('seeker_terms', models.TextField(blank=True, verbose_name='Support seeker terms / needs')),
                ('peer_terms', models.TextField(blank=True, verbose_name='Peer terms of engagement')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe payment intent ID')),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe checkout session ID')),
                ('requested_start_time', models.DateTimeField(blank=True, help_text='The start time requested by the support seeker for a 1:1 meeting.', null=True, verbose_name='Requested start time')),
                ('requested_duration_minutes', models.PositiveIntegerField(blank=True, help_text='The duration requested by the support seeker (5-120 minutes).', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='Requested duration (minutes)')),
                ('meeting_link', models.URLField(blank=True, help_text='Auto-populated with a Whereby meeting link close to the time of the event if left empty. Only valid for 1:1 meetings.', verbose_name='Meeting link')),
                ('whereby_meeting_id', models.CharField(blank=True, max_length=255, verbose_name='Whereby meeting ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='meetings.meeting')),
                ('support_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingsBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('meetings', models.ManyToManyField(blank=True, related_name='bookmarks', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('status', django_fsm.FSMField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20, protected=True, verbose_name='Status')),
                ('stripe_refund_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe refund ID')),
                ('peer_response', models.TextField(blank=True, verbose_name='Peer response')),
                ('meeting_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='meetings.meetingrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('meeting_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='meetings.meetingrequest')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='meetingrequest',
            constraint=models.UniqueConstraint(fields=('meeting', 'support_seeker'), name='meetings_meetingrequest_unique_meeting_per_seeker'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'scheduled_at'], name='meeting_status_sched_idx'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('peer', 'title'), name='meetings_meeting_unique_published_title_per_peer'),
        ),
    ]
