# Generated by Django 6.0.8 on 2026-10-05 19:35

import django.db.models.deletion
import modelcluster.fields
import taggit.managers
import wagtail_daisIE.pages
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('taxonomy', '0001_initial'),
        ('wagtail_daisIE', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='support_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingformpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='bookingformpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='bookingformpage',
            name='success_redirect_page',
            field=models.ForeignKey(blank=True, help_text='Redirect here after a successful submission instead of the body.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Success redirect'),
        ),
        migrations.AddField(
            model_name='bookingformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='meetings.bookingformpage'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='taxonomy.country', verbose_name='Countries'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='meetings', to='taxonomy.language'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meetingformpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='meetingformpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='meetingformpage',
            name='success_redirect_page',
            field=models.ForeignKey(blank=True, help_text='Redirect here after a successful submission instead of the body.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Success redirect'),
        ),
        migrations.AddField(
            model_name='meetingformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='meetings.meetingformpage'),
        ),
        migrations.AddField(
            model_name='meetingpricetier',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meetingpriceoption',
            name='tier',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='meetings.meetingpricetier'),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='meetings.booking'),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='support_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingsbookmark',
            name='meetings',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meetingsbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingtag',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meetingtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_items', to='taxonomy.allowedtag'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='meetings.MeetingTag', to='taxonomy.AllowedTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, help_text='Recurrence rule for group meetings. Not applicable to 1:1 meetings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='meetings.recurrencerule'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='meeting_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='meetings.meetingrequest'),
        ),
        migrations.AddField(
            model_name='refundrequestformpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='refundrequestformpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='refundrequestformpage',
            name='success_redirect_page',
            field=models.ForeignKey(blank=True, help_text='Redirect here after a successful submission instead of the body.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Success redirect'),
        ),
        migrations.AddField(
            model_name='refundrequestformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='meetings.refundrequestformpage'),
        ),
        migrations.AddField(
            model_name='review',
            name='meeting_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='meetings.meetingrequest'),
        ),
        migrations.AddField(
            model_name='review',
            name='peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewformpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='reviewformpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='reviewformpage',
            name='success_redirect_page',
            field=models.ForeignKey(blank=True, help_text='Redirect here after a successful submission instead of the body.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Success redirect'),
        ),
        migrations.AddField(
            model_name='reviewformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='meetings.reviewformpage'),
        ),
        migrations.AddConstraint(
            model_name='meetingpricetier',
            constraint=models.UniqueConstraint(fields=('meeting', 'duration_minutes'), name='meetings_meetingpricetier_unique_duration'),
        ),
        migrations.AddConstraint(
            model_name='meetingrequest',
            constraint=models.UniqueConstraint(fields=('booking', 'requested_start_time'), name='meetings_meetingrequest_unique_session_per_booking'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'scheduled_at'], name='meeting_status_sched_idx'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'published')), fields=('peer', 'title'), name='meetings_meeting_unique_published_title_per_peer'),
        ),
    ]
