# Generated by Django 6.0.6 on 2026-09-08 19:30

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_periodic_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=django_fsm.FSMField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='status',
            field=django_fsm.FSMField(choices=[('pending_approval', 'Pending approval'), ('pending_payment', 'Pending payment'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_approval', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=django_fsm.FSMField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
