# Generated by Django 6.0.8 on 2026-10-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaisieBridgeSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('label', models.CharField(help_text='Human readable name shown in the Wagtail admin.', max_length=255, verbose_name='Label')),
                ('event_type', models.CharField(choices=[('booking_requested', 'Booking requested'), ('booking_approved', 'Booking approved'), ('booking_rejected', 'Booking rejected'), ('booking_paid', 'Booking paid'), ('booking_completed', 'Booking completed'), ('booking_cancelled', 'Booking cancelled'), ('refund_requested', 'Refund requested'), ('refund_approved', 'Refund approved'), ('refund_rejected', 'Refund rejected'), ('refund_refunded', 'Refund issued'), ('review_created', 'Review created'), ('peer_approved', 'Peer approved'), ('peer_application_approved', 'Peer application approved'), ('peer_application_rejected', 'Peer application rejected'), ('subscription_created', 'Subscription created'), ('subscription_cancelled', 'Subscription cancelled'), ('payment_reminder_due', 'Payment reminder due'), ('meeting_upcoming', 'Upcoming meeting'), ('meeting_cancelled', 'Cancelled meeting'), ('session_reminder_1d', 'Session reminder (1 day)'), ('session_reminder_1h', 'Session reminder (1 hour)'), ('account_created', 'Account created'), ('account_deleted', 'Account deleted'), ('account_degraded', 'Account degraded'), ('peer_published_meeting', 'Care provider published a meeting'), ('payment_succeeded', 'Payment succeeded'), ('payment_failed', 'Payment failed')], help_text='The event this subscriber reacts to.', max_length=50, verbose_name='Event type')),
                ('is_active', models.BooleanField(default=True, help_text='Only active subscribers receive events from the bus.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Daisie email bridge',
                'verbose_name_plural': 'Daisie email bridges',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('disabled_event_types', models.JSONField(blank=True, default=list, help_text='Event types this member has opted out of.', verbose_name='Disabled event types')),
            ],
            options={
                'verbose_name': 'Notification preference',
                'verbose_name_plural': 'Notification preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('event_type', models.CharField(choices=[('booking_requested', 'Booking requested'), ('booking_approved', 'Booking approved'), ('booking_rejected', 'Booking rejected'), ('booking_paid', 'Booking paid'), ('booking_completed', 'Booking completed'), ('booking_cancelled', 'Booking cancelled'), ('refund_requested', 'Refund requested'), ('refund_approved', 'Refund approved'), ('refund_rejected', 'Refund rejected'), ('refund_refunded', 'Refund issued'), ('review_created', 'Review created'), ('peer_approved', 'Peer approved'), ('peer_application_approved', 'Peer application approved'), ('peer_application_rejected', 'Peer application rejected'), ('subscription_created', 'Subscription created'), ('subscription_cancelled', 'Subscription cancelled'), ('payment_reminder_due', 'Payment reminder due'), ('meeting_upcoming', 'Upcoming meeting'), ('meeting_cancelled', 'Cancelled meeting'), ('session_reminder_1d', 'Session reminder (1 day)'), ('session_reminder_1h', 'Session reminder (1 hour)'), ('account_created', 'Account created'), ('account_deleted', 'Account deleted'), ('account_degraded', 'Account degraded'), ('peer_published_meeting', 'Care provider published a meeting'), ('payment_succeeded', 'Payment succeeded'), ('payment_failed', 'Payment failed')], db_index=True, max_length=50, verbose_name='Event type')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('event_ref', models.CharField(blank=True, db_index=True, help_text='Stable reference used to dedupe events, e.g. meetingrequest.42.cancelled.', max_length=255, verbose_name='Event reference')),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='recorded', help_text='Delivery state reserved for future notification channels.', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Notification event log',
                'verbose_name_plural': 'Notification event logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'event_ref'], name='notif_event_type_ref_idx')],
            },
        ),
    ]
