# Generated by Django 6.0.6 on 2026-09-06 16:30

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0003_2_11'),
        ('payments', '__first__'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('reason', models.TextField(verbose_name='Reason for applying')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('submission', models.JSONField(blank=True, null=True, verbose_name='Submission')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Peer applications',
            },
        ),
        migrations.CreateModel(
            name='PeerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('start', models.DateTimeField(verbose_name='Start of unavailable window')),
                ('end', models.DateTimeField(verbose_name='End of unavailable window')),
                ('reason', models.CharField(blank=True, help_text='Optional reason for blocking this time window.', max_length=255, verbose_name='Reason')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peer availability block',
                'verbose_name_plural': 'Peer availability blocks',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='PeerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved by moderator')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved at')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified by moderator')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_peers', to=settings.AUTH_USER_MODEL)),
                ('languages', models.ManyToManyField(blank=True, related_name='peers', to='taxonomy.language')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_peers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peer profile',
                'verbose_name_plural': 'Peer profiles',
            },
        ),
        migrations.CreateModel(
            name='PeersBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('peers', models.ManyToManyField(blank=True, related_name='bookmarks', to='peers.peerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('payment_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_subscription', to='payments.paymentprofile')),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_subscription', to='djstripe.subscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
