# Generated by Django 6.0.6 on 2026-09-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('reason', models.TextField(verbose_name='Reason for applying')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('submission', models.JSONField(blank=True, null=True, verbose_name='Submission')),
            ],
            options={
                'verbose_name_plural': 'Peer applications',
            },
        ),
        migrations.CreateModel(
            name='PeerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('start', models.DateTimeField(verbose_name='Start of unavailable window')),
                ('end', models.DateTimeField(verbose_name='End of unavailable window')),
                ('reason', models.CharField(blank=True, help_text='Optional reason for blocking this time window.', max_length=255, verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'Peer availability block',
                'verbose_name_plural': 'Peer availability blocks',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='PeerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved by moderator')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved at')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified by moderator')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified at')),
            ],
            options={
                'verbose_name': 'Peer profile',
                'verbose_name_plural': 'Peer profiles',
            },
        ),
        migrations.CreateModel(
            name='PeersBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
