# Generated by Django 6.0.8 on 2026-10-05 19:35

import django.db.models.deletion
import modelcluster.fields
import taggit.managers
import wagtail_daisIE.pages
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0003_2_11'),
        ('payments', '0002_initial'),
        ('peers', '0001_initial'),
        ('taxonomy', '0001_initial'),
        ('wagtail_daisIE', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.WAGTAIL_PAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='peerapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peerapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peerapplicationformpage',
            name='audience_denied_page',
            field=models.ForeignKey(blank=True, help_text='Used when the denial behaviour is redirect.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Redirect target'),
        ),
        migrations.AddField(
            model_name='peerapplicationformpage',
            name='page_theme',
            field=models.ForeignKey(blank=True, default=wagtail_daisIE.pages.get_default_theme_id, help_text='Select a DaisyUI theme to style this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtail_daisIE.daisyuitheme'),
        ),
        migrations.AddField(
            model_name='peerapplicationformpage',
            name='success_redirect_page',
            field=models.ForeignKey(blank=True, help_text='Redirect here after a successful submission instead of the body.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.WAGTAIL_PAGE_MODEL, verbose_name='Success redirect'),
        ),
        migrations.AddField(
            model_name='peerapplicationformfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='peers.peerapplicationformpage'),
        ),
        migrations.AddField(
            model_name='peeravailability',
            name='peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peerprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_peers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peerprofile',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='peers', to='taxonomy.country', verbose_name='Countries'),
        ),
        migrations.AddField(
            model_name='peerprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='peers', to='taxonomy.language'),
        ),
        migrations.AddField(
            model_name='peerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peerprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_peers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peerprofiletag',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peers.peerprofile'),
        ),
        migrations.AddField(
            model_name='peerprofiletag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_profile_items', to='taxonomy.allowedtag'),
        ),
        migrations.AddField(
            model_name='peerprofile',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='peers.PeerProfileTag', to='taxonomy.AllowedTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='peersbookmark',
            name='peers',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='peers.peerprofile'),
        ),
        migrations.AddField(
            model_name='peersbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peersubscription',
            name='payment_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_subscription', to='payments.paymentprofile'),
        ),
        migrations.AddField(
            model_name='peersubscription',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_subscription', to='djstripe.subscription'),
        ),
        migrations.AddIndex(
            model_name='peerprofile',
            index=models.Index(fields=['is_approved'], name='peers_peerprofile_approved_idx'),
        ),
    ]
