# Generated by Django 6.0.6 on 2026-09-08 18:17

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0003_2_11'),
        ('payments', '0002_initial'),
        ('peers', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('taxonomy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='peerapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peerapplication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peeravailability',
            name='peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peerprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_peers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peerprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='peers', to='taxonomy.language'),
        ),
        migrations.AddField(
            model_name='peerprofile',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='peerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peerprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_peers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peersbookmark',
            name='peers',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='peers.peerprofile'),
        ),
        migrations.AddField(
            model_name='peersbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers_bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='peersubscription',
            name='payment_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_subscription', to='payments.paymentprofile'),
        ),
        migrations.AddField(
            model_name='peersubscription',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_subscription', to='djstripe.subscription'),
        ),
        migrations.AddIndex(
            model_name='peerprofile',
            index=models.Index(fields=['is_approved'], name='peers_peerprofile_approved_idx'),
        ),
    ]
