#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py migrate --noinput
python /app/manage.py ensure_superuser
python /app/manage.py collectstatic --noinput

exec gunicorn config.wsgi \
--bind 0.0.0.0:5000 \
--workers=${NUM_WORKERS:-4} \
--threads=${NUM_THREADS:-2} \
--chdir=/app \
--log-level=info \
--log-file=/var/log/django/gunicorn.log \
--preload
