"""
Custom Wagtail widgets for enhanced admin UX.
"""

import json

from django import forms
from django.utils.safestring import mark_safe

# Curated emoji categories for the picker - organized for practical use
# Rather than auto-categorizing 1900+ emojis, this provides a sensible subset
EMOJI_CATEGORIES = {
    "smileys": {
        "label": "Smileys & People",
        "icon": "😀",
        "emojis": [
            {
                "emoji": "😀",
                "name": "grinning face",
                "keywords": ["happy", "smile", "joy"],
            },
            {
                "emoji": "😃",
                "name": "grinning face with big eyes",
                "keywords": ["happy", "smile"],
            },
            {
                "emoji": "😄",
                "name": "grinning face with smiling eyes",
                "keywords": ["happy", "joy"],
            },
            {"emoji": "😁", "name": "beaming face", "keywords": ["happy", "grin"]},
            {
                "emoji": "😅",
                "name": "grinning face with sweat",
                "keywords": ["nervous", "awkward"],
            },
            {
                "emoji": "😂",
                "name": "face with tears of joy",
                "keywords": ["laugh", "funny"],
            },
            {
                "emoji": "🤣",
                "name": "rolling on the floor laughing",
                "keywords": ["laugh", "lol"],
            },
            {
                "emoji": "😊",
                "name": "smiling face with smiling eyes",
                "keywords": ["blush", "happy"],
            },
            {
                "emoji": "😇",
                "name": "smiling face with halo",
                "keywords": ["angel", "innocent"],
            },
            {"emoji": "🙂", "name": "slightly smiling face", "keywords": ["smile"]},
            {
                "emoji": "🙃",
                "name": "upside-down face",
                "keywords": ["silly", "sarcasm"],
            },
            {"emoji": "😉", "name": "winking face", "keywords": ["wink", "flirt"]},
            {"emoji": "😌", "name": "relieved face", "keywords": ["relief", "calm"]},
            {
                "emoji": "😍",
                "name": "smiling face with heart-eyes",
                "keywords": ["love", "crush"],
            },
            {
                "emoji": "🥰",
                "name": "smiling face with hearts",
                "keywords": ["love", "adore"],
            },
            {
                "emoji": "😘",
                "name": "face blowing a kiss",
                "keywords": ["kiss", "love"],
            },
            {"emoji": "😗", "name": "kissing face", "keywords": ["kiss"]},
            {
                "emoji": "😙",
                "name": "kissing face with smiling eyes",
                "keywords": ["kiss"],
            },
            {
                "emoji": "🥲",
                "name": "smiling face with tear",
                "keywords": ["grateful", "touched"],
            },
            {
                "emoji": "😋",
                "name": "face savoring food",
                "keywords": ["yummy", "delicious"],
            },
            {
                "emoji": "😛",
                "name": "face with tongue",
                "keywords": ["playful", "silly"],
            },
            {
                "emoji": "😜",
                "name": "winking face with tongue",
                "keywords": ["crazy", "playful"],
            },
            {"emoji": "🤪", "name": "zany face", "keywords": ["crazy", "wild"]},
            {
                "emoji": "😝",
                "name": "squinting face with tongue",
                "keywords": ["playful"],
            },
            {"emoji": "🤑", "name": "money-mouth face", "keywords": ["rich", "money"]},
            {"emoji": "🤗", "name": "hugging face", "keywords": ["hug", "warm"]},
            {
                "emoji": "🤭",
                "name": "face with hand over mouth",
                "keywords": ["oops", "giggle"],
            },
            {"emoji": "🤫", "name": "shushing face", "keywords": ["quiet", "secret"]},
            {"emoji": "🤔", "name": "thinking face", "keywords": ["think", "hmm"]},
            {
                "emoji": "🤐",
                "name": "zipper-mouth face",
                "keywords": ["quiet", "secret"],
            },
            {
                "emoji": "🤨",
                "name": "face with raised eyebrow",
                "keywords": ["skeptical"],
            },
            {"emoji": "😐", "name": "neutral face", "keywords": ["meh", "indifferent"]},
            {"emoji": "😑", "name": "expressionless face", "keywords": ["blank"]},
            {"emoji": "😶", "name": "face without mouth", "keywords": ["silent"]},
            {"emoji": "😏", "name": "smirking face", "keywords": ["smug", "smirk"]},
            {
                "emoji": "😒",
                "name": "unamused face",
                "keywords": ["meh", "unimpressed"],
            },
            {
                "emoji": "🙄",
                "name": "face with rolling eyes",
                "keywords": ["eyeroll", "whatever"],
            },
            {
                "emoji": "😬",
                "name": "grimacing face",
                "keywords": ["awkward", "nervous"],
            },
            {"emoji": "🤥", "name": "lying face", "keywords": ["lie", "pinocchio"]},
            {"emoji": "😔", "name": "pensive face", "keywords": ["sad", "thoughtful"]},
            {"emoji": "😪", "name": "sleepy face", "keywords": ["tired", "sleep"]},
            {"emoji": "🤤", "name": "drooling face", "keywords": ["hungry", "want"]},
            {"emoji": "😴", "name": "sleeping face", "keywords": ["sleep", "zzz"]},
            {
                "emoji": "😷",
                "name": "face with medical mask",
                "keywords": ["sick", "mask"],
            },
            {
                "emoji": "🤒",
                "name": "face with thermometer",
                "keywords": ["sick", "fever"],
            },
            {
                "emoji": "🤕",
                "name": "face with head-bandage",
                "keywords": ["hurt", "injured"],
            },
            {"emoji": "🤢", "name": "nauseated face", "keywords": ["sick", "gross"]},
            {"emoji": "🤮", "name": "face vomiting", "keywords": ["sick", "vomit"]},
            {"emoji": "🤧", "name": "sneezing face", "keywords": ["sick", "achoo"]},
            {"emoji": "🥵", "name": "hot face", "keywords": ["hot", "sweating"]},
            {"emoji": "🥶", "name": "cold face", "keywords": ["cold", "freezing"]},
            {"emoji": "🥴", "name": "woozy face", "keywords": ["drunk", "dizzy"]},
            {"emoji": "😵", "name": "dizzy face", "keywords": ["dizzy", "dead"]},
            {
                "emoji": "🤯",
                "name": "exploding head",
                "keywords": ["mind blown", "shocked"],
            },
            {
                "emoji": "🤠",
                "name": "cowboy hat face",
                "keywords": ["cowboy", "yeehaw"],
            },
            {
                "emoji": "🥳",
                "name": "partying face",
                "keywords": ["party", "celebrate"],
            },
            {
                "emoji": "🥸",
                "name": "disguised face",
                "keywords": ["disguise", "incognito"],
            },
            {
                "emoji": "😎",
                "name": "smiling face with sunglasses",
                "keywords": ["cool", "sunglasses"],
            },
            {"emoji": "🤓", "name": "nerd face", "keywords": ["nerd", "geek"]},
            {
                "emoji": "🧐",
                "name": "face with monocle",
                "keywords": ["thinking", "smart"],
            },
            {
                "emoji": "😕",
                "name": "confused face",
                "keywords": ["confused", "puzzled"],
            },
            {"emoji": "😟", "name": "worried face", "keywords": ["worried", "concern"]},
            {
                "emoji": "🙁",
                "name": "slightly frowning face",
                "keywords": ["sad", "frown"],
            },
            {
                "emoji": "😮",
                "name": "face with open mouth",
                "keywords": ["surprised", "wow"],
            },
            {
                "emoji": "😯",
                "name": "hushed face",
                "keywords": ["surprised", "stunned"],
            },
            {
                "emoji": "😲",
                "name": "astonished face",
                "keywords": ["shocked", "amazed"],
            },
            {
                "emoji": "😳",
                "name": "flushed face",
                "keywords": ["embarrassed", "blush"],
            },
            {
                "emoji": "🥺",
                "name": "pleading face",
                "keywords": ["puppy eyes", "please"],
            },
            {
                "emoji": "😦",
                "name": "frowning face with open mouth",
                "keywords": ["aw", "sad"],
            },
            {
                "emoji": "😧",
                "name": "anguished face",
                "keywords": ["stunned", "anguish"],
            },
            {"emoji": "😨", "name": "fearful face", "keywords": ["scared", "fear"]},
            {
                "emoji": "😰",
                "name": "anxious face with sweat",
                "keywords": ["nervous", "anxious"],
            },
            {
                "emoji": "😥",
                "name": "sad but relieved face",
                "keywords": ["relieved", "sad"],
            },
            {"emoji": "😢", "name": "crying face", "keywords": ["cry", "sad", "tear"]},
            {
                "emoji": "😭",
                "name": "loudly crying face",
                "keywords": ["sob", "cry", "sad"],
            },
            {
                "emoji": "😱",
                "name": "face screaming in fear",
                "keywords": ["scream", "scared"],
            },
            {
                "emoji": "😖",
                "name": "confounded face",
                "keywords": ["quivering", "upset"],
            },
            {
                "emoji": "😣",
                "name": "persevering face",
                "keywords": ["struggle", "endure"],
            },
            {
                "emoji": "😞",
                "name": "disappointed face",
                "keywords": ["sad", "disappointed"],
            },
            {
                "emoji": "😓",
                "name": "downcast face with sweat",
                "keywords": ["tired", "stressed"],
            },
            {"emoji": "😩", "name": "weary face", "keywords": ["tired", "weary"]},
            {"emoji": "😫", "name": "tired face", "keywords": ["exhausted", "tired"]},
            {
                "emoji": "🥱",
                "name": "yawning face",
                "keywords": ["yawn", "tired", "bored"],
            },
            {
                "emoji": "😤",
                "name": "face with steam from nose",
                "keywords": ["angry", "triumph"],
            },
            {"emoji": "😡", "name": "pouting face", "keywords": ["angry", "rage"]},
            {"emoji": "😠", "name": "angry face", "keywords": ["angry", "mad"]},
            {
                "emoji": "🤬",
                "name": "face with symbols on mouth",
                "keywords": ["swearing", "angry"],
            },
            {
                "emoji": "😈",
                "name": "smiling face with horns",
                "keywords": ["devil", "evil"],
            },
            {
                "emoji": "👿",
                "name": "angry face with horns",
                "keywords": ["devil", "angry"],
            },
            {"emoji": "💀", "name": "skull", "keywords": ["dead", "death", "skeleton"]},
            {
                "emoji": "☠️",
                "name": "skull and crossbones",
                "keywords": ["death", "danger"],
            },
            {
                "emoji": "👻",
                "name": "ghost",
                "keywords": ["ghost", "halloween", "spooky"],
            },
            {"emoji": "👽", "name": "alien", "keywords": ["alien", "ufo", "space"]},
            {"emoji": "🤖", "name": "robot", "keywords": ["robot", "bot", "tech"]},
            {
                "emoji": "🎃",
                "name": "jack-o-lantern",
                "keywords": ["halloween", "pumpkin"],
            },
        ],
    },
    "gestures": {
        "label": "Gestures & Body",
        "icon": "👋",
        "emojis": [
            {
                "emoji": "👋",
                "name": "waving hand",
                "keywords": ["hello", "goodbye", "wave"],
            },
            {
                "emoji": "🤚",
                "name": "raised back of hand",
                "keywords": ["stop", "hand"],
            },
            {
                "emoji": "🖐️",
                "name": "hand with fingers splayed",
                "keywords": ["hand", "five"],
            },
            {"emoji": "✋", "name": "raised hand", "keywords": ["stop", "high five"]},
            {
                "emoji": "🖖",
                "name": "vulcan salute",
                "keywords": ["spock", "star trek"],
            },
            {"emoji": "👌", "name": "OK hand", "keywords": ["ok", "perfect", "good"]},
            {"emoji": "🤌", "name": "pinched fingers", "keywords": ["italian", "what"]},
            {"emoji": "🤏", "name": "pinching hand", "keywords": ["small", "tiny"]},
            {
                "emoji": "✌️",
                "name": "victory hand",
                "keywords": ["peace", "victory", "two"],
            },
            {"emoji": "🤞", "name": "crossed fingers", "keywords": ["luck", "hope"]},
            {"emoji": "🤟", "name": "love-you gesture", "keywords": ["love", "rock"]},
            {"emoji": "🤘", "name": "sign of the horns", "keywords": ["rock", "metal"]},
            {"emoji": "🤙", "name": "call me hand", "keywords": ["call", "shaka"]},
            {
                "emoji": "👈",
                "name": "backhand index pointing left",
                "keywords": ["left", "point"],
            },
            {
                "emoji": "👉",
                "name": "backhand index pointing right",
                "keywords": ["right", "point"],
            },
            {
                "emoji": "👆",
                "name": "backhand index pointing up",
                "keywords": ["up", "point"],
            },
            {
                "emoji": "👇",
                "name": "backhand index pointing down",
                "keywords": ["down", "point"],
            },
            {
                "emoji": "☝️",
                "name": "index pointing up",
                "keywords": ["up", "one", "point"],
            },
            {
                "emoji": "👍",
                "name": "thumbs up",
                "keywords": ["like", "good", "approve"],
            },
            {
                "emoji": "👎",
                "name": "thumbs down",
                "keywords": ["dislike", "bad", "disapprove"],
            },
            {
                "emoji": "✊",
                "name": "raised fist",
                "keywords": ["fist", "power", "punch"],
            },
            {
                "emoji": "👊",
                "name": "oncoming fist",
                "keywords": ["punch", "fist bump"],
            },
            {"emoji": "🤛", "name": "left-facing fist", "keywords": ["fist bump"]},
            {"emoji": "🤜", "name": "right-facing fist", "keywords": ["fist bump"]},
            {"emoji": "👏", "name": "clapping hands", "keywords": ["clap", "applause"]},
            {
                "emoji": "🙌",
                "name": "raising hands",
                "keywords": ["celebration", "hooray"],
            },
            {"emoji": "👐", "name": "open hands", "keywords": ["hands", "open"]},
            {
                "emoji": "🤲",
                "name": "palms up together",
                "keywords": ["prayer", "cupped"],
            },
            {"emoji": "🤝", "name": "handshake", "keywords": ["deal", "agreement"]},
            {
                "emoji": "🙏",
                "name": "folded hands",
                "keywords": ["pray", "please", "thanks"],
            },
            {"emoji": "✍️", "name": "writing hand", "keywords": ["write", "sign"]},
            {
                "emoji": "💪",
                "name": "flexed biceps",
                "keywords": ["strong", "muscle", "power"],
            },
            {
                "emoji": "🦾",
                "name": "mechanical arm",
                "keywords": ["robot", "prosthetic"],
            },
            {
                "emoji": "🦿",
                "name": "mechanical leg",
                "keywords": ["robot", "prosthetic"],
            },
            {"emoji": "🦵", "name": "leg", "keywords": ["kick", "limb"]},
            {"emoji": "🦶", "name": "foot", "keywords": ["kick", "stomp"]},
            {"emoji": "👂", "name": "ear", "keywords": ["hear", "listen"]},
            {"emoji": "👃", "name": "nose", "keywords": ["smell", "sniff"]},
            {"emoji": "🧠", "name": "brain", "keywords": ["smart", "think", "mind"]},
            {"emoji": "👀", "name": "eyes", "keywords": ["look", "see", "watch"]},
            {"emoji": "👁️", "name": "eye", "keywords": ["look", "see"]},
            {"emoji": "👅", "name": "tongue", "keywords": ["taste", "lick"]},
            {"emoji": "👄", "name": "mouth", "keywords": ["lips", "kiss"]},
        ],
    },
    "hearts": {
        "label": "Hearts & Love",
        "icon": "❤️",
        "emojis": [
            {
                "emoji": "❤️",
                "name": "red heart",
                "keywords": ["love", "heart", "romance"],
            },
            {"emoji": "🧡", "name": "orange heart", "keywords": ["love", "heart"]},
            {
                "emoji": "💛",
                "name": "yellow heart",
                "keywords": ["love", "heart", "friendship"],
            },
            {
                "emoji": "💚",
                "name": "green heart",
                "keywords": ["love", "heart", "nature"],
            },
            {
                "emoji": "💙",
                "name": "blue heart",
                "keywords": ["love", "heart", "trust"],
            },
            {"emoji": "💜", "name": "purple heart", "keywords": ["love", "heart"]},
            {
                "emoji": "🖤",
                "name": "black heart",
                "keywords": ["love", "heart", "dark"],
            },
            {
                "emoji": "🤍",
                "name": "white heart",
                "keywords": ["love", "heart", "pure"],
            },
            {"emoji": "🤎", "name": "brown heart", "keywords": ["love", "heart"]},
            {"emoji": "💔", "name": "broken heart", "keywords": ["heartbreak", "sad"]},
            {"emoji": "❤️‍🔥", "name": "heart on fire", "keywords": ["passion", "love"]},
            {
                "emoji": "❤️‍🩹",
                "name": "mending heart",
                "keywords": ["healing", "recovery"],
            },
            {"emoji": "💕", "name": "two hearts", "keywords": ["love", "romance"]},
            {
                "emoji": "💞",
                "name": "revolving hearts",
                "keywords": ["love", "romance"],
            },
            {"emoji": "💓", "name": "beating heart", "keywords": ["love", "heartbeat"]},
            {"emoji": "💗", "name": "growing heart", "keywords": ["love", "affection"]},
            {"emoji": "💖", "name": "sparkling heart", "keywords": ["love", "sparkle"]},
            {"emoji": "💘", "name": "heart with arrow", "keywords": ["love", "cupid"]},
            {"emoji": "💝", "name": "heart with ribbon", "keywords": ["love", "gift"]},
            {"emoji": "💟", "name": "heart decoration", "keywords": ["love", "cute"]},
            {"emoji": "💌", "name": "love letter", "keywords": ["letter", "romance"]},
            {"emoji": "💋", "name": "kiss mark", "keywords": ["kiss", "lipstick"]},
            {"emoji": "🫶", "name": "heart hands", "keywords": ["love", "gesture"]},
        ],
    },
    "animals": {
        "label": "Animals & Nature",
        "icon": "🐶",
        "emojis": [
            {"emoji": "🐶", "name": "dog face", "keywords": ["dog", "puppy", "pet"]},
            {"emoji": "🐱", "name": "cat face", "keywords": ["cat", "kitten", "pet"]},
            {"emoji": "🐭", "name": "mouse face", "keywords": ["mouse", "rodent"]},
            {"emoji": "🐹", "name": "hamster", "keywords": ["hamster", "pet"]},
            {"emoji": "🐰", "name": "rabbit face", "keywords": ["rabbit", "bunny"]},
            {"emoji": "🦊", "name": "fox", "keywords": ["fox", "clever"]},
            {"emoji": "🐻", "name": "bear", "keywords": ["bear", "teddy"]},
            {"emoji": "🐼", "name": "panda", "keywords": ["panda", "bear"]},
            {"emoji": "🐨", "name": "koala", "keywords": ["koala", "australia"]},
            {"emoji": "🐯", "name": "tiger face", "keywords": ["tiger", "cat"]},
            {"emoji": "🦁", "name": "lion", "keywords": ["lion", "king"]},
            {"emoji": "🐮", "name": "cow face", "keywords": ["cow", "moo"]},
            {"emoji": "🐷", "name": "pig face", "keywords": ["pig", "oink"]},
            {"emoji": "🐸", "name": "frog", "keywords": ["frog", "toad"]},
            {"emoji": "🐵", "name": "monkey face", "keywords": ["monkey", "ape"]},
            {
                "emoji": "🙈",
                "name": "see-no-evil monkey",
                "keywords": ["monkey", "hide"],
            },
            {
                "emoji": "🙉",
                "name": "hear-no-evil monkey",
                "keywords": ["monkey", "deaf"],
            },
            {
                "emoji": "🙊",
                "name": "speak-no-evil monkey",
                "keywords": ["monkey", "quiet"],
            },
            {"emoji": "🐔", "name": "chicken", "keywords": ["chicken", "bird"]},
            {"emoji": "🐧", "name": "penguin", "keywords": ["penguin", "bird"]},
            {"emoji": "🐦", "name": "bird", "keywords": ["bird", "fly"]},
            {"emoji": "🐤", "name": "baby chick", "keywords": ["chick", "bird"]},
            {"emoji": "🦆", "name": "duck", "keywords": ["duck", "bird"]},
            {"emoji": "🦅", "name": "eagle", "keywords": ["eagle", "bird"]},
            {"emoji": "🦉", "name": "owl", "keywords": ["owl", "bird", "wise"]},
            {"emoji": "🦇", "name": "bat", "keywords": ["bat", "vampire"]},
            {"emoji": "🐺", "name": "wolf", "keywords": ["wolf", "howl"]},
            {"emoji": "🐗", "name": "boar", "keywords": ["boar", "pig"]},
            {"emoji": "🐴", "name": "horse face", "keywords": ["horse", "pony"]},
            {"emoji": "🦄", "name": "unicorn", "keywords": ["unicorn", "magic"]},
            {"emoji": "🐝", "name": "honeybee", "keywords": ["bee", "honey"]},
            {"emoji": "🐛", "name": "bug", "keywords": ["bug", "insect"]},
            {"emoji": "🦋", "name": "butterfly", "keywords": ["butterfly", "insect"]},
            {"emoji": "🐌", "name": "snail", "keywords": ["snail", "slow"]},
            {"emoji": "🐙", "name": "octopus", "keywords": ["octopus", "sea"]},
            {"emoji": "🦑", "name": "squid", "keywords": ["squid", "sea"]},
            {"emoji": "🦐", "name": "shrimp", "keywords": ["shrimp", "seafood"]},
            {"emoji": "🦞", "name": "lobster", "keywords": ["lobster", "seafood"]},
            {"emoji": "🦀", "name": "crab", "keywords": ["crab", "seafood"]},
            {"emoji": "🐠", "name": "tropical fish", "keywords": ["fish", "tropical"]},
            {"emoji": "🐟", "name": "fish", "keywords": ["fish", "sea"]},
            {"emoji": "🐬", "name": "dolphin", "keywords": ["dolphin", "sea"]},
            {"emoji": "🐳", "name": "spouting whale", "keywords": ["whale", "sea"]},
            {"emoji": "🦈", "name": "shark", "keywords": ["shark", "sea", "danger"]},
            {
                "emoji": "🐊",
                "name": "crocodile",
                "keywords": ["crocodile", "alligator"],
            },
            {"emoji": "🐢", "name": "turtle", "keywords": ["turtle", "slow"]},
            {"emoji": "🦎", "name": "lizard", "keywords": ["lizard", "reptile"]},
            {"emoji": "🐍", "name": "snake", "keywords": ["snake", "reptile"]},
            {"emoji": "🐲", "name": "dragon face", "keywords": ["dragon", "fantasy"]},
            {"emoji": "🐉", "name": "dragon", "keywords": ["dragon", "fantasy"]},
            {"emoji": "🦕", "name": "sauropod", "keywords": ["dinosaur", "dino"]},
            {"emoji": "🦖", "name": "T-Rex", "keywords": ["dinosaur", "dino"]},
        ],
    },
    "nature": {
        "label": "Plants & Weather",
        "icon": "🌸",
        "emojis": [
            {"emoji": "🌸", "name": "cherry blossom", "keywords": ["flower", "spring"]},
            {"emoji": "💐", "name": "bouquet", "keywords": ["flowers", "gift"]},
            {"emoji": "🌷", "name": "tulip", "keywords": ["flower", "spring"]},
            {"emoji": "🌹", "name": "rose", "keywords": ["flower", "love", "romance"]},
            {"emoji": "🌺", "name": "hibiscus", "keywords": ["flower", "tropical"]},
            {"emoji": "🌻", "name": "sunflower", "keywords": ["flower", "sun"]},
            {"emoji": "🌼", "name": "blossom", "keywords": ["flower", "nature"]},
            {"emoji": "🌱", "name": "seedling", "keywords": ["plant", "grow"]},
            {"emoji": "🌲", "name": "evergreen tree", "keywords": ["tree", "forest"]},
            {"emoji": "🌳", "name": "deciduous tree", "keywords": ["tree", "nature"]},
            {"emoji": "🌴", "name": "palm tree", "keywords": ["tree", "tropical"]},
            {"emoji": "🌵", "name": "cactus", "keywords": ["plant", "desert"]},
            {"emoji": "🌾", "name": "sheaf of rice", "keywords": ["grain", "harvest"]},
            {"emoji": "🍀", "name": "four leaf clover", "keywords": ["luck", "irish"]},
            {"emoji": "🍁", "name": "maple leaf", "keywords": ["fall", "autumn"]},
            {"emoji": "🍂", "name": "fallen leaf", "keywords": ["fall", "autumn"]},
            {
                "emoji": "🍃",
                "name": "leaf fluttering in wind",
                "keywords": ["leaf", "wind"],
            },
            {"emoji": "☀️", "name": "sun", "keywords": ["sun", "sunny", "weather"]},
            {
                "emoji": "🌤️",
                "name": "sun behind small cloud",
                "keywords": ["weather", "cloudy"],
            },
            {
                "emoji": "⛅",
                "name": "sun behind cloud",
                "keywords": ["weather", "cloudy"],
            },
            {
                "emoji": "🌥️",
                "name": "sun behind large cloud",
                "keywords": ["weather", "cloudy"],
            },
            {"emoji": "☁️", "name": "cloud", "keywords": ["cloud", "weather"]},
            {
                "emoji": "🌦️",
                "name": "sun behind rain cloud",
                "keywords": ["weather", "rain"],
            },
            {"emoji": "🌧️", "name": "cloud with rain", "keywords": ["rain", "weather"]},
            {
                "emoji": "⛈️",
                "name": "cloud with lightning and rain",
                "keywords": ["storm", "thunder"],
            },
            {
                "emoji": "🌩️",
                "name": "cloud with lightning",
                "keywords": ["lightning", "storm"],
            },
            {
                "emoji": "❄️",
                "name": "snowflake",
                "keywords": ["snow", "winter", "cold"],
            },
            {"emoji": "🌨️", "name": "cloud with snow", "keywords": ["snow", "weather"]},
            {"emoji": "☃️", "name": "snowman", "keywords": ["snow", "winter"]},
            {
                "emoji": "⛄",
                "name": "snowman without snow",
                "keywords": ["snow", "winter"],
            },
            {"emoji": "🌈", "name": "rainbow", "keywords": ["rainbow", "weather"]},
            {"emoji": "🔥", "name": "fire", "keywords": ["fire", "hot", "flame"]},
            {"emoji": "💧", "name": "droplet", "keywords": ["water", "drop"]},
            {"emoji": "🌊", "name": "water wave", "keywords": ["wave", "ocean", "sea"]},
            {"emoji": "⭐", "name": "star", "keywords": ["star", "night"]},
            {"emoji": "🌟", "name": "glowing star", "keywords": ["star", "sparkle"]},
            {"emoji": "✨", "name": "sparkles", "keywords": ["sparkle", "magic"]},
            {"emoji": "💫", "name": "dizzy", "keywords": ["star", "dizzy"]},
            {"emoji": "🌙", "name": "crescent moon", "keywords": ["moon", "night"]},
            {"emoji": "🌕", "name": "full moon", "keywords": ["moon", "night"]},
        ],
    },
    "food": {
        "label": "Food & Drink",
        "icon": "🍔",
        "emojis": [
            {"emoji": "🍎", "name": "red apple", "keywords": ["apple", "fruit"]},
            {"emoji": "🍊", "name": "tangerine", "keywords": ["orange", "fruit"]},
            {"emoji": "🍋", "name": "lemon", "keywords": ["lemon", "fruit"]},
            {"emoji": "🍌", "name": "banana", "keywords": ["banana", "fruit"]},
            {"emoji": "🍉", "name": "watermelon", "keywords": ["watermelon", "fruit"]},
            {"emoji": "🍇", "name": "grapes", "keywords": ["grapes", "fruit"]},
            {"emoji": "🍓", "name": "strawberry", "keywords": ["strawberry", "fruit"]},
            {"emoji": "🍒", "name": "cherries", "keywords": ["cherry", "fruit"]},
            {"emoji": "🍑", "name": "peach", "keywords": ["peach", "fruit"]},
            {"emoji": "🥭", "name": "mango", "keywords": ["mango", "fruit"]},
            {"emoji": "🍍", "name": "pineapple", "keywords": ["pineapple", "fruit"]},
            {"emoji": "🥥", "name": "coconut", "keywords": ["coconut", "tropical"]},
            {"emoji": "🥑", "name": "avocado", "keywords": ["avocado", "vegetable"]},
            {"emoji": "🍆", "name": "eggplant", "keywords": ["eggplant", "vegetable"]},
            {"emoji": "🥕", "name": "carrot", "keywords": ["carrot", "vegetable"]},
            {"emoji": "🌽", "name": "ear of corn", "keywords": ["corn", "vegetable"]},
            {"emoji": "🌶️", "name": "hot pepper", "keywords": ["pepper", "spicy"]},
            {"emoji": "🥒", "name": "cucumber", "keywords": ["cucumber", "vegetable"]},
            {
                "emoji": "🥬",
                "name": "leafy green",
                "keywords": ["lettuce", "vegetable"],
            },
            {"emoji": "🥦", "name": "broccoli", "keywords": ["broccoli", "vegetable"]},
            {"emoji": "🧄", "name": "garlic", "keywords": ["garlic", "vegetable"]},
            {"emoji": "🧅", "name": "onion", "keywords": ["onion", "vegetable"]},
            {"emoji": "🍄", "name": "mushroom", "keywords": ["mushroom", "vegetable"]},
            {"emoji": "🥜", "name": "peanuts", "keywords": ["peanut", "nut"]},
            {"emoji": "🍞", "name": "bread", "keywords": ["bread", "toast"]},
            {"emoji": "🥐", "name": "croissant", "keywords": ["croissant", "pastry"]},
            {"emoji": "🥖", "name": "baguette bread", "keywords": ["bread", "french"]},
            {"emoji": "🥨", "name": "pretzel", "keywords": ["pretzel", "snack"]},
            {"emoji": "🧀", "name": "cheese wedge", "keywords": ["cheese", "dairy"]},
            {"emoji": "🥚", "name": "egg", "keywords": ["egg", "breakfast"]},
            {
                "emoji": "🍳",
                "name": "cooking",
                "keywords": ["egg", "breakfast", "frying"],
            },
            {"emoji": "🥓", "name": "bacon", "keywords": ["bacon", "breakfast"]},
            {"emoji": "🥩", "name": "cut of meat", "keywords": ["meat", "steak"]},
            {"emoji": "🍗", "name": "poultry leg", "keywords": ["chicken", "meat"]},
            {"emoji": "🍖", "name": "meat on bone", "keywords": ["meat", "bone"]},
            {"emoji": "🌭", "name": "hot dog", "keywords": ["hotdog", "sausage"]},
            {"emoji": "🍔", "name": "hamburger", "keywords": ["burger", "fast food"]},
            {"emoji": "🍟", "name": "french fries", "keywords": ["fries", "fast food"]},
            {"emoji": "🍕", "name": "pizza", "keywords": ["pizza", "fast food"]},
            {"emoji": "🥪", "name": "sandwich", "keywords": ["sandwich", "lunch"]},
            {"emoji": "🌮", "name": "taco", "keywords": ["taco", "mexican"]},
            {"emoji": "🌯", "name": "burrito", "keywords": ["burrito", "mexican"]},
            {"emoji": "🥗", "name": "green salad", "keywords": ["salad", "healthy"]},
            {"emoji": "🍝", "name": "spaghetti", "keywords": ["pasta", "italian"]},
            {"emoji": "🍜", "name": "steaming bowl", "keywords": ["noodles", "ramen"]},
            {"emoji": "🍲", "name": "pot of food", "keywords": ["stew", "soup"]},
            {"emoji": "🍛", "name": "curry rice", "keywords": ["curry", "indian"]},
            {"emoji": "🍣", "name": "sushi", "keywords": ["sushi", "japanese"]},
            {"emoji": "🍱", "name": "bento box", "keywords": ["bento", "japanese"]},
            {"emoji": "🍩", "name": "doughnut", "keywords": ["donut", "dessert"]},
            {"emoji": "🍪", "name": "cookie", "keywords": ["cookie", "dessert"]},
            {"emoji": "🎂", "name": "birthday cake", "keywords": ["cake", "birthday"]},
            {"emoji": "🍰", "name": "shortcake", "keywords": ["cake", "dessert"]},
            {"emoji": "🧁", "name": "cupcake", "keywords": ["cupcake", "dessert"]},
            {
                "emoji": "🍦",
                "name": "soft ice cream",
                "keywords": ["ice cream", "dessert"],
            },
            {"emoji": "🍨", "name": "ice cream", "keywords": ["ice cream", "dessert"]},
            {
                "emoji": "🍫",
                "name": "chocolate bar",
                "keywords": ["chocolate", "candy"],
            },
            {"emoji": "🍬", "name": "candy", "keywords": ["candy", "sweet"]},
            {"emoji": "🍭", "name": "lollipop", "keywords": ["lollipop", "candy"]},
            {
                "emoji": "☕",
                "name": "hot beverage",
                "keywords": ["coffee", "tea", "drink"],
            },
            {
                "emoji": "🍵",
                "name": "teacup without handle",
                "keywords": ["tea", "drink"],
            },
            {"emoji": "🧃", "name": "beverage box", "keywords": ["juice", "drink"]},
            {"emoji": "🥤", "name": "cup with straw", "keywords": ["soda", "drink"]},
            {"emoji": "🧋", "name": "bubble tea", "keywords": ["boba", "drink"]},
            {"emoji": "🍺", "name": "beer mug", "keywords": ["beer", "drink"]},
            {
                "emoji": "🍻",
                "name": "clinking beer mugs",
                "keywords": ["beer", "cheers"],
            },
            {
                "emoji": "🥂",
                "name": "clinking glasses",
                "keywords": ["champagne", "cheers"],
            },
            {"emoji": "🍷", "name": "wine glass", "keywords": ["wine", "drink"]},
            {
                "emoji": "🍸",
                "name": "cocktail glass",
                "keywords": ["cocktail", "drink"],
            },
            {
                "emoji": "🍹",
                "name": "tropical drink",
                "keywords": ["cocktail", "tropical"],
            },
        ],
    },
    "activities": {
        "label": "Activities & Sports",
        "icon": "⚽",
        "emojis": [
            {
                "emoji": "⚽",
                "name": "soccer ball",
                "keywords": ["soccer", "football", "sport"],
            },
            {"emoji": "🏀", "name": "basketball", "keywords": ["basketball", "sport"]},
            {
                "emoji": "🏈",
                "name": "american football",
                "keywords": ["football", "sport"],
            },
            {"emoji": "⚾", "name": "baseball", "keywords": ["baseball", "sport"]},
            {"emoji": "🥎", "name": "softball", "keywords": ["softball", "sport"]},
            {"emoji": "🎾", "name": "tennis", "keywords": ["tennis", "sport"]},
            {"emoji": "🏐", "name": "volleyball", "keywords": ["volleyball", "sport"]},
            {"emoji": "🏉", "name": "rugby football", "keywords": ["rugby", "sport"]},
            {"emoji": "🥏", "name": "flying disc", "keywords": ["frisbee", "sport"]},
            {"emoji": "🎱", "name": "pool 8 ball", "keywords": ["billiards", "pool"]},
            {"emoji": "🏓", "name": "ping pong", "keywords": ["table tennis", "sport"]},
            {"emoji": "🏸", "name": "badminton", "keywords": ["badminton", "sport"]},
            {"emoji": "🏒", "name": "ice hockey", "keywords": ["hockey", "sport"]},
            {"emoji": "🥅", "name": "goal net", "keywords": ["goal", "sport"]},
            {"emoji": "⛳", "name": "flag in hole", "keywords": ["golf", "sport"]},
            {"emoji": "🏹", "name": "bow and arrow", "keywords": ["archery", "sport"]},
            {"emoji": "🎣", "name": "fishing pole", "keywords": ["fishing", "sport"]},
            {"emoji": "🥊", "name": "boxing glove", "keywords": ["boxing", "sport"]},
            {
                "emoji": "🥋",
                "name": "martial arts uniform",
                "keywords": ["karate", "sport"],
            },
            {"emoji": "🎿", "name": "skis", "keywords": ["ski", "winter", "sport"]},
            {"emoji": "⛷️", "name": "skier", "keywords": ["ski", "winter", "sport"]},
            {"emoji": "🏂", "name": "snowboarder", "keywords": ["snowboard", "winter"]},
            {"emoji": "🏄", "name": "person surfing", "keywords": ["surf", "beach"]},
            {"emoji": "🏊", "name": "person swimming", "keywords": ["swim", "sport"]},
            {"emoji": "🚴", "name": "person biking", "keywords": ["bike", "cycling"]},
            {
                "emoji": "🧘",
                "name": "person in lotus position",
                "keywords": ["yoga", "meditation"],
            },
            {"emoji": "🎮", "name": "video game", "keywords": ["game", "controller"]},
            {"emoji": "🕹️", "name": "joystick", "keywords": ["game", "arcade"]},
            {"emoji": "🎲", "name": "game die", "keywords": ["dice", "game"]},
            {"emoji": "♟️", "name": "chess pawn", "keywords": ["chess", "game"]},
            {"emoji": "🎯", "name": "direct hit", "keywords": ["target", "bullseye"]},
            {"emoji": "🎳", "name": "bowling", "keywords": ["bowling", "sport"]},
            {
                "emoji": "🎪",
                "name": "circus tent",
                "keywords": ["circus", "entertainment"],
            },
            {
                "emoji": "🎭",
                "name": "performing arts",
                "keywords": ["theater", "drama"],
            },
            {"emoji": "🎨", "name": "artist palette", "keywords": ["art", "paint"]},
            {"emoji": "🎬", "name": "clapper board", "keywords": ["movie", "film"]},
            {
                "emoji": "🎤",
                "name": "microphone",
                "keywords": ["mic", "sing", "karaoke"],
            },
            {"emoji": "🎧", "name": "headphone", "keywords": ["music", "audio"]},
            {"emoji": "🎼", "name": "musical score", "keywords": ["music", "notes"]},
            {"emoji": "🎹", "name": "musical keyboard", "keywords": ["piano", "music"]},
            {"emoji": "🥁", "name": "drum", "keywords": ["drum", "music"]},
            {"emoji": "🎷", "name": "saxophone", "keywords": ["sax", "music"]},
            {"emoji": "🎺", "name": "trumpet", "keywords": ["trumpet", "music"]},
            {"emoji": "🎸", "name": "guitar", "keywords": ["guitar", "music"]},
            {"emoji": "🎻", "name": "violin", "keywords": ["violin", "music"]},
            {
                "emoji": "🏆",
                "name": "trophy",
                "keywords": ["trophy", "winner", "award"],
            },
            {
                "emoji": "🥇",
                "name": "1st place medal",
                "keywords": ["gold", "medal", "first"],
            },
            {
                "emoji": "🥈",
                "name": "2nd place medal",
                "keywords": ["silver", "medal", "second"],
            },
            {
                "emoji": "🥉",
                "name": "3rd place medal",
                "keywords": ["bronze", "medal", "third"],
            },
            {"emoji": "🏅", "name": "sports medal", "keywords": ["medal", "winner"]},
            {"emoji": "🎖️", "name": "military medal", "keywords": ["medal", "honor"]},
        ],
    },
    "travel": {
        "label": "Travel & Places",
        "icon": "✈️",
        "emojis": [
            {"emoji": "🚗", "name": "automobile", "keywords": ["car", "vehicle"]},
            {"emoji": "🚕", "name": "taxi", "keywords": ["taxi", "cab"]},
            {"emoji": "🚌", "name": "bus", "keywords": ["bus", "transit"]},
            {"emoji": "🚎", "name": "trolleybus", "keywords": ["bus", "transit"]},
            {"emoji": "🚐", "name": "minibus", "keywords": ["van", "vehicle"]},
            {
                "emoji": "🚑",
                "name": "ambulance",
                "keywords": ["ambulance", "emergency"],
            },
            {
                "emoji": "🚒",
                "name": "fire engine",
                "keywords": ["fire truck", "emergency"],
            },
            {"emoji": "🚓", "name": "police car", "keywords": ["police", "emergency"]},
            {"emoji": "🚲", "name": "bicycle", "keywords": ["bike", "cycling"]},
            {
                "emoji": "🛵",
                "name": "motor scooter",
                "keywords": ["scooter", "vehicle"],
            },
            {
                "emoji": "🏍️",
                "name": "motorcycle",
                "keywords": ["motorcycle", "vehicle"],
            },
            {"emoji": "🚂", "name": "locomotive", "keywords": ["train", "rail"]},
            {"emoji": "🚃", "name": "railway car", "keywords": ["train", "rail"]},
            {"emoji": "🚄", "name": "high-speed train", "keywords": ["train", "fast"]},
            {
                "emoji": "🚅",
                "name": "bullet train",
                "keywords": ["train", "shinkansen"],
            },
            {
                "emoji": "✈️",
                "name": "airplane",
                "keywords": ["plane", "flight", "travel"],
            },
            {
                "emoji": "🛫",
                "name": "airplane departure",
                "keywords": ["takeoff", "flight"],
            },
            {
                "emoji": "🛬",
                "name": "airplane arrival",
                "keywords": ["landing", "flight"],
            },
            {
                "emoji": "🚀",
                "name": "rocket",
                "keywords": ["rocket", "space", "launch"],
            },
            {"emoji": "🛸", "name": "flying saucer", "keywords": ["ufo", "alien"]},
            {"emoji": "🚁", "name": "helicopter", "keywords": ["helicopter", "flight"]},
            {"emoji": "🛥️", "name": "motor boat", "keywords": ["boat", "water"]},
            {"emoji": "⛵", "name": "sailboat", "keywords": ["boat", "sailing"]},
            {"emoji": "🚢", "name": "ship", "keywords": ["ship", "cruise"]},
            {"emoji": "⚓", "name": "anchor", "keywords": ["anchor", "ship"]},
            {"emoji": "🏠", "name": "house", "keywords": ["house", "home"]},
            {"emoji": "🏡", "name": "house with garden", "keywords": ["house", "home"]},
            {
                "emoji": "🏢",
                "name": "office building",
                "keywords": ["office", "building"],
            },
            {
                "emoji": "🏣",
                "name": "Japanese post office",
                "keywords": ["post", "building"],
            },
            {"emoji": "🏥", "name": "hospital", "keywords": ["hospital", "health"]},
            {"emoji": "🏦", "name": "bank", "keywords": ["bank", "finance"]},
            {"emoji": "🏨", "name": "hotel", "keywords": ["hotel", "lodging"]},
            {"emoji": "🏩", "name": "love hotel", "keywords": ["hotel", "love"]},
            {"emoji": "🏪", "name": "convenience store", "keywords": ["store", "shop"]},
            {"emoji": "🏫", "name": "school", "keywords": ["school", "education"]},
            {"emoji": "🏬", "name": "department store", "keywords": ["store", "shop"]},
            {"emoji": "🏭", "name": "factory", "keywords": ["factory", "industry"]},
            {"emoji": "🏯", "name": "Japanese castle", "keywords": ["castle", "japan"]},
            {"emoji": "🏰", "name": "castle", "keywords": ["castle", "medieval"]},
            {"emoji": "💒", "name": "wedding", "keywords": ["wedding", "church"]},
            {"emoji": "🗼", "name": "Tokyo tower", "keywords": ["tower", "tokyo"]},
            {
                "emoji": "🗽",
                "name": "Statue of Liberty",
                "keywords": ["liberty", "new york"],
            },
            {"emoji": "⛪", "name": "church", "keywords": ["church", "religion"]},
            {"emoji": "🕌", "name": "mosque", "keywords": ["mosque", "islam"]},
            {"emoji": "🛕", "name": "hindu temple", "keywords": ["temple", "hindu"]},
            {"emoji": "🕍", "name": "synagogue", "keywords": ["synagogue", "jewish"]},
            {"emoji": "⛩️", "name": "shinto shrine", "keywords": ["shrine", "japan"]},
            {"emoji": "🕋", "name": "kaaba", "keywords": ["kaaba", "mecca"]},
            {"emoji": "⛲", "name": "fountain", "keywords": ["fountain", "park"]},
            {"emoji": "⛺", "name": "tent", "keywords": ["tent", "camping"]},
            {"emoji": "🌁", "name": "foggy", "keywords": ["fog", "weather"]},
            {"emoji": "🌃", "name": "night with stars", "keywords": ["night", "city"]},
            {
                "emoji": "🌄",
                "name": "sunrise over mountains",
                "keywords": ["sunrise", "mountain"],
            },
            {"emoji": "🌅", "name": "sunrise", "keywords": ["sunrise", "morning"]},
            {
                "emoji": "🌆",
                "name": "cityscape at dusk",
                "keywords": ["city", "evening"],
            },
            {"emoji": "🌇", "name": "sunset", "keywords": ["sunset", "evening"]},
            {"emoji": "🌉", "name": "bridge at night", "keywords": ["bridge", "night"]},
            {"emoji": "🗺️", "name": "world map", "keywords": ["map", "world"]},
            {"emoji": "🧭", "name": "compass", "keywords": ["compass", "navigation"]},
            {
                "emoji": "🏔️",
                "name": "snow-capped mountain",
                "keywords": ["mountain", "snow"],
            },
            {"emoji": "⛰️", "name": "mountain", "keywords": ["mountain", "nature"]},
            {"emoji": "🏕️", "name": "camping", "keywords": ["camping", "tent"]},
            {
                "emoji": "🏖️",
                "name": "beach with umbrella",
                "keywords": ["beach", "vacation"],
            },
            {"emoji": "🏜️", "name": "desert", "keywords": ["desert", "hot"]},
            {
                "emoji": "🏝️",
                "name": "desert island",
                "keywords": ["island", "tropical"],
            },
        ],
    },
    "objects": {
        "label": "Objects & Tools",
        "icon": "💡",
        "emojis": [
            {"emoji": "⌚", "name": "watch", "keywords": ["watch", "time"]},
            {
                "emoji": "📱",
                "name": "mobile phone",
                "keywords": ["phone", "mobile", "cell"],
            },
            {"emoji": "💻", "name": "laptop", "keywords": ["laptop", "computer"]},
            {"emoji": "🖥️", "name": "desktop computer", "keywords": ["computer", "pc"]},
            {"emoji": "🖨️", "name": "printer", "keywords": ["printer", "office"]},
            {"emoji": "⌨️", "name": "keyboard", "keywords": ["keyboard", "typing"]},
            {
                "emoji": "🖱️",
                "name": "computer mouse",
                "keywords": ["mouse", "computer"],
            },
            {"emoji": "💾", "name": "floppy disk", "keywords": ["save", "disk"]},
            {"emoji": "💿", "name": "optical disk", "keywords": ["cd", "disk"]},
            {"emoji": "📀", "name": "dvd", "keywords": ["dvd", "disk"]},
            {"emoji": "📷", "name": "camera", "keywords": ["camera", "photo"]},
            {"emoji": "📹", "name": "video camera", "keywords": ["camera", "video"]},
            {"emoji": "🎥", "name": "movie camera", "keywords": ["movie", "film"]},
            {"emoji": "📺", "name": "television", "keywords": ["tv", "television"]},
            {"emoji": "📻", "name": "radio", "keywords": ["radio", "audio"]},
            {"emoji": "🔦", "name": "flashlight", "keywords": ["flashlight", "light"]},
            {
                "emoji": "💡",
                "name": "light bulb",
                "keywords": ["idea", "light", "bulb"],
            },
            {"emoji": "🔌", "name": "electric plug", "keywords": ["plug", "electric"]},
            {"emoji": "🔋", "name": "battery", "keywords": ["battery", "power"]},
            {"emoji": "🔧", "name": "wrench", "keywords": ["tool", "fix"]},
            {"emoji": "🔨", "name": "hammer", "keywords": ["tool", "build"]},
            {"emoji": "🔩", "name": "nut and bolt", "keywords": ["tool", "hardware"]},
            {"emoji": "⚙️", "name": "gear", "keywords": ["settings", "cog"]},
            {"emoji": "🔗", "name": "link", "keywords": ["link", "chain"]},
            {"emoji": "📎", "name": "paperclip", "keywords": ["paperclip", "office"]},
            {"emoji": "✂️", "name": "scissors", "keywords": ["scissors", "cut"]},
            {"emoji": "📏", "name": "straight ruler", "keywords": ["ruler", "measure"]},
            {
                "emoji": "📐",
                "name": "triangular ruler",
                "keywords": ["ruler", "triangle"],
            },
            {"emoji": "📌", "name": "pushpin", "keywords": ["pin", "location"]},
            {"emoji": "📍", "name": "round pushpin", "keywords": ["pin", "location"]},
            {"emoji": "🔒", "name": "locked", "keywords": ["lock", "secure"]},
            {"emoji": "🔓", "name": "unlocked", "keywords": ["unlock", "open"]},
            {"emoji": "🔑", "name": "key", "keywords": ["key", "unlock"]},
            {"emoji": "🗝️", "name": "old key", "keywords": ["key", "vintage"]},
            {"emoji": "🔐", "name": "locked with key", "keywords": ["lock", "secure"]},
            {"emoji": "📦", "name": "package", "keywords": ["box", "delivery"]},
            {"emoji": "📧", "name": "e-mail", "keywords": ["email", "mail"]},
            {"emoji": "📨", "name": "incoming envelope", "keywords": ["email", "mail"]},
            {
                "emoji": "📩",
                "name": "envelope with arrow",
                "keywords": ["email", "send"],
            },
            {"emoji": "📝", "name": "memo", "keywords": ["note", "write"]},
            {"emoji": "📁", "name": "file folder", "keywords": ["folder", "file"]},
            {"emoji": "📂", "name": "open file folder", "keywords": ["folder", "file"]},
            {"emoji": "📅", "name": "calendar", "keywords": ["calendar", "date"]},
            {
                "emoji": "📆",
                "name": "tear-off calendar",
                "keywords": ["calendar", "date"],
            },
            {
                "emoji": "📈",
                "name": "chart increasing",
                "keywords": ["chart", "graph", "growth"],
            },
            {
                "emoji": "📉",
                "name": "chart decreasing",
                "keywords": ["chart", "graph", "decline"],
            },
            {
                "emoji": "📊",
                "name": "bar chart",
                "keywords": ["chart", "graph", "stats"],
            },
            {"emoji": "📋", "name": "clipboard", "keywords": ["clipboard", "list"]},
            {"emoji": "📌", "name": "pushpin", "keywords": ["pin", "tack"]},
            {"emoji": "📕", "name": "closed book", "keywords": ["book", "read"]},
            {"emoji": "📖", "name": "open book", "keywords": ["book", "read"]},
            {"emoji": "📚", "name": "books", "keywords": ["books", "library"]},
            {"emoji": "🎁", "name": "wrapped gift", "keywords": ["gift", "present"]},
            {"emoji": "🎀", "name": "ribbon", "keywords": ["ribbon", "bow"]},
            {"emoji": "🏷️", "name": "label", "keywords": ["tag", "label"]},
            {"emoji": "💰", "name": "money bag", "keywords": ["money", "rich"]},
            {"emoji": "💵", "name": "dollar banknote", "keywords": ["money", "dollar"]},
            {"emoji": "💳", "name": "credit card", "keywords": ["card", "payment"]},
            {"emoji": "💎", "name": "gem stone", "keywords": ["diamond", "gem"]},
            {"emoji": "⚖️", "name": "balance scale", "keywords": ["scale", "justice"]},
            {"emoji": "🧲", "name": "magnet", "keywords": ["magnet", "attract"]},
            {
                "emoji": "⏰",
                "name": "alarm clock",
                "keywords": ["clock", "alarm", "time"],
            },
            {"emoji": "⏱️", "name": "stopwatch", "keywords": ["stopwatch", "timer"]},
            {"emoji": "⏳", "name": "hourglass", "keywords": ["hourglass", "time"]},
        ],
    },
    "symbols": {
        "label": "Symbols",
        "icon": "✅",
        "emojis": [
            {
                "emoji": "✅",
                "name": "check mark button",
                "keywords": ["check", "done", "yes"],
            },
            {"emoji": "❌", "name": "cross mark", "keywords": ["no", "wrong", "x"]},
            {"emoji": "❓", "name": "question mark", "keywords": ["question", "help"]},
            {
                "emoji": "❗",
                "name": "exclamation mark",
                "keywords": ["exclamation", "warning"],
            },
            {
                "emoji": "‼️",
                "name": "double exclamation mark",
                "keywords": ["exclamation", "warning"],
            },
            {"emoji": "⭕", "name": "hollow red circle", "keywords": ["circle", "o"]},
            {"emoji": "🔴", "name": "red circle", "keywords": ["red", "circle"]},
            {"emoji": "🟠", "name": "orange circle", "keywords": ["orange", "circle"]},
            {"emoji": "🟡", "name": "yellow circle", "keywords": ["yellow", "circle"]},
            {"emoji": "🟢", "name": "green circle", "keywords": ["green", "circle"]},
            {"emoji": "🔵", "name": "blue circle", "keywords": ["blue", "circle"]},
            {"emoji": "🟣", "name": "purple circle", "keywords": ["purple", "circle"]},
            {"emoji": "⚫", "name": "black circle", "keywords": ["black", "circle"]},
            {"emoji": "⚪", "name": "white circle", "keywords": ["white", "circle"]},
            {"emoji": "🟤", "name": "brown circle", "keywords": ["brown", "circle"]},
            {
                "emoji": "🔺",
                "name": "red triangle pointed up",
                "keywords": ["triangle", "up"],
            },
            {
                "emoji": "🔻",
                "name": "red triangle pointed down",
                "keywords": ["triangle", "down"],
            },
            {
                "emoji": "🔷",
                "name": "large blue diamond",
                "keywords": ["diamond", "blue"],
            },
            {
                "emoji": "🔶",
                "name": "large orange diamond",
                "keywords": ["diamond", "orange"],
            },
            {
                "emoji": "🔸",
                "name": "small orange diamond",
                "keywords": ["diamond", "orange"],
            },
            {
                "emoji": "🔹",
                "name": "small blue diamond",
                "keywords": ["diamond", "blue"],
            },
            {
                "emoji": "▪️",
                "name": "black small square",
                "keywords": ["square", "black"],
            },
            {
                "emoji": "▫️",
                "name": "white small square",
                "keywords": ["square", "white"],
            },
            {
                "emoji": "◾",
                "name": "black medium-small square",
                "keywords": ["square", "black"],
            },
            {
                "emoji": "◽",
                "name": "white medium-small square",
                "keywords": ["square", "white"],
            },
            {
                "emoji": "⬛",
                "name": "black large square",
                "keywords": ["square", "black"],
            },
            {
                "emoji": "⬜",
                "name": "white large square",
                "keywords": ["square", "white"],
            },
            {"emoji": "➕", "name": "plus", "keywords": ["plus", "add"]},
            {"emoji": "➖", "name": "minus", "keywords": ["minus", "subtract"]},
            {"emoji": "➗", "name": "divide", "keywords": ["divide", "division"]},
            {"emoji": "✖️", "name": "multiply", "keywords": ["multiply", "x"]},
            {"emoji": "♾️", "name": "infinity", "keywords": ["infinity", "forever"]},
            {"emoji": "💯", "name": "hundred points", "keywords": ["100", "perfect"]},
            {"emoji": "🔢", "name": "input numbers", "keywords": ["numbers", "123"]},
            {"emoji": "#️⃣", "name": "keycap: #", "keywords": ["hashtag", "number"]},
            {"emoji": "*️⃣", "name": "keycap: *", "keywords": ["asterisk", "star"]},
            {"emoji": "0️⃣", "name": "keycap: 0", "keywords": ["zero", "0"]},
            {"emoji": "1️⃣", "name": "keycap: 1", "keywords": ["one", "1"]},
            {"emoji": "2️⃣", "name": "keycap: 2", "keywords": ["two", "2"]},
            {"emoji": "3️⃣", "name": "keycap: 3", "keywords": ["three", "3"]},
            {"emoji": "4️⃣", "name": "keycap: 4", "keywords": ["four", "4"]},
            {"emoji": "5️⃣", "name": "keycap: 5", "keywords": ["five", "5"]},
            {"emoji": "6️⃣", "name": "keycap: 6", "keywords": ["six", "6"]},
            {"emoji": "7️⃣", "name": "keycap: 7", "keywords": ["seven", "7"]},
            {"emoji": "8️⃣", "name": "keycap: 8", "keywords": ["eight", "8"]},
            {"emoji": "9️⃣", "name": "keycap: 9", "keywords": ["nine", "9"]},
            {"emoji": "🔟", "name": "keycap: 10", "keywords": ["ten", "10"]},
            {
                "emoji": "🔠",
                "name": "input latin uppercase",
                "keywords": ["abc", "letters"],
            },
            {
                "emoji": "🔡",
                "name": "input latin lowercase",
                "keywords": ["abc", "letters"],
            },
            {"emoji": "ℹ️", "name": "information", "keywords": ["info", "information"]},
            {"emoji": "🆗", "name": "OK button", "keywords": ["ok", "okay"]},
            {"emoji": "🆕", "name": "NEW button", "keywords": ["new"]},
            {"emoji": "🆙", "name": "UP! button", "keywords": ["up"]},
            {"emoji": "🆒", "name": "COOL button", "keywords": ["cool"]},
            {"emoji": "🆓", "name": "FREE button", "keywords": ["free"]},
            {
                "emoji": "🔤",
                "name": "input latin letters",
                "keywords": ["abc", "alphabet"],
            },
            {"emoji": "🔣", "name": "input symbols", "keywords": ["symbols"]},
            {"emoji": "⚠️", "name": "warning", "keywords": ["warning", "caution"]},
            {"emoji": "🚫", "name": "prohibited", "keywords": ["no", "forbidden"]},
            {
                "emoji": "🚸",
                "name": "children crossing",
                "keywords": ["children", "school"],
            },
            {"emoji": "⛔", "name": "no entry", "keywords": ["stop", "forbidden"]},
            {"emoji": "📵", "name": "no mobile phones", "keywords": ["no phone"]},
            {
                "emoji": "🔞",
                "name": "no one under eighteen",
                "keywords": ["18+", "adult"],
            },
            {
                "emoji": "♻️",
                "name": "recycling symbol",
                "keywords": ["recycle", "green"],
            },
            {
                "emoji": "🔰",
                "name": "Japanese symbol for beginner",
                "keywords": ["beginner"],
            },
            {"emoji": "🎵", "name": "musical note", "keywords": ["music", "note"]},
            {"emoji": "🎶", "name": "musical notes", "keywords": ["music", "notes"]},
            {"emoji": "©️", "name": "copyright", "keywords": ["copyright", "c"]},
            {"emoji": "®️", "name": "registered", "keywords": ["registered", "r"]},
            {"emoji": "™️", "name": "trade mark", "keywords": ["trademark", "tm"]},
        ],
    },
}


def get_categorized_emojis():
    """
    Return the curated emoji categories.
    This is a pre-defined, sensible subset rather than auto-categorizing
    the entire emoji library.
    """
    return EMOJI_CATEGORIES


class EmojiPickerWidget(forms.TextInput):
    """
    A text input with an emoji picker popup for Wagtail admin.
    Uses vanilla JS - no React required.
    """

    template_name = "wagtailadmin/widgets/emoji_picker.html"

    def __init__(self, attrs=None):
        default_attrs = {"class": "emoji-picker-input", "readonly": "readonly"}
        if attrs:
            default_attrs.update(attrs)
        super().__init__(attrs=default_attrs)

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        context["emoji_categories"] = get_categorized_emojis()
        context["emoji_categories_json"] = mark_safe(
            json.dumps(get_categorized_emojis())
        )
        return context

    class Media:
        css = {"all": ("css/emoji_picker.css",)}
        js = ("js/emoji_picker.js",)
