"""
Custom Wagtail widgets for enhanced admin UX.
"""

import json

from django import forms
from django.utils.safestring import mark_safe
from emoji import EMOJI_DATA

# Curated emoji categories for the picker - organized for practical use
# Rather than auto-categorizing 1900+ emojis, this provides a sensible subset
EMOJI_CATEGORY_KEYS = [
    "smileys",
    "gestures",
    "hearts",
    "animals_nature",
    "food",
    "activities",
    "travel",
    "objects",
    "symbols",
]

CATEGORY_KEYWORDS = {
    "activities": [
        "medal",
        "ball",
        "christmas_tree",
        "japanese_dolls",
        "suit",
        "admission_tickets",
        "american_football",
        "artist_palette",
        "badminton",
        "balloon",
        "baseball",
        "basketball",
        "bowling",
        "boxing_glove",
        "carp_streamer",
        "chess_pawn",
        "club_suit",
        "confetti_ball",
        "cricket_game",
        "crystal_ball",
        "curling_stone",
        "diamond_suit",
        "direct_hit",
        "diving_mask",
        "field_hockey",
        "firecracker",
        "fireworks",
        "fishing_pole",
        "flag_in_hole",
        "flower_playing_cards",
        "flying_disc",
        "framed_picture",
        "game_die",
        "goal_net",
        "heart_suit",
        "ice_hockey",
        "ice_skate",
        "jack-o-lantern",
        "joker",
        "joystick",
        "kite",
        "lacrosse",
        "mahjong_red_dragon",
        "martial_arts_uniform",
        "military_medal",
        "moon_viewing_ceremony",
        "nazar_amulet",
        "party_popper",
        "performing_arts",
        "pine_decoration",
        "ping_pong",
        "pool_8_ball",
        "puzzle_piece",
        "red_envelope",
        "reminder_ribbon",
        "ribbon",
        "rugby_football",
        "running_shirt",
        "skis",
        "sled",
        "slot_machine",
        "soccer_ball",
        "softball",
        "spade_suit",
        "sparkler",
        "sparkles",
        "sports_medal",
        "tanabata_tree",
        "teddy_bear",
        "tennis",
        "thread",
        "ticket",
        "trophy",
        "video_game",
        "volleyball",
        "wind_chime",
        "wrapped_gift",
        "yarn",
        "yo-yo",
    ],
    "animals_nature": [
        "leaf",
        "t-rex",
        "ant",
        "baby_chick",
        "badger",
        "bat",
        "bear",
        "bird",
        "blossom",
        "blowfish",
        "boar",
        "bouquet",
        "bug",
        "butterfly",
        "cactus",
        "camel",
        "cat",
        "cat_face",
        "cherry_blossom",
        "chicken",
        "chipmunk",
        "cow",
        "cow_face",
        "cricket",
        "crocodile",
        "deciduous_tree",
        "deer",
        "dog",
        "dog_face",
        "dolphin",
        "dove",
        "dragon",
        "dragon_face",
        "duck",
        "eagle",
        "elephant",
        "evergreen_tree",
        "ewe",
        "fallen_leaf",
        "fish",
        "flamingo",
        "four_leaf_clover",
        "fox",
        "frog",
        "front-facing_baby_chick",
        "giraffe",
        "goat",
        "gorilla",
        "guide_dog",
        "hamster",
        "hatching_chick",
        "hedgehog",
        "herb",
        "hibiscus",
        "hippopotamus",
        "honeybee",
        "horse",
        "horse_face",
        "kangaroo",
        "koala",
        "lady_beetle",
        "leaf_fluttering_in_wind",
        "leopard",
        "lion",
        "lizard",
        "llama",
        "maple_leaf",
        "microbe",
        "monkey",
        "monkey_face",
        "mosquito",
        "mouse",
        "mouse_face",
        "octopus",
        "orangutan",
        "otter",
        "owl",
        "ox",
        "palm_tree",
        "panda",
        "parrot",
        "paw_prints",
        "peacock",
        "penguin",
        "pig",
        "pig_face",
        "pig_nose",
        "poodle",
        "rabbit",
        "rabbit_face",
        "raccoon",
        "ram",
        "rat",
        "rhinoceros",
        "rooster",
        "rose",
        "rosette",
        "sauropod",
        "scorpion",
        "seedling",
        "service_dog",
        "shamrock",
        "shark",
        "sheaf_of_rice",
        "skunk",
        "sloth",
        "snail",
        "snake",
        "spider",
        "spider_web",
        "spiral_shell",
        "spouting_whale",
        "sunflower",
        "swan",
        "tiger",
        "tiger_face",
        "tropical_fish",
        "tulip",
        "turkey",
        "turtle",
        "two-hump_camel",
        "unicorn",
        "water_buffalo",
        "whale",
        "white_flower",
        "wilted_flower",
        "wolf",
        "zebra",
    ],
    "food": [
        "glass",
        "rice",
        "with",
        "amphora",
        "avocado",
        "baby_bottle",
        "bacon",
        "bagel",
        "baguette_bread",
        "banana",
        "beer_mug",
        "bento_box",
        "beverage_box",
        "birthday_cake",
        "bottle_with_popping_cork",
        "bowl_with_spoon",
        "bread",
        "broccoli",
        "burrito",
        "butter",
        "candy",
        "canned_food",
        "carrot",
        "cheese_wedge",
        "cherries",
        "chestnut",
        "chocolate_bar",
        "chopsticks",
        "clinking_beer_mugs",
        "clinking_glasses",
        "cocktail_glass",
        "coconut",
        "cooked_rice",
        "cookie",
        "cooking",
        "crab",
        "croissant",
        "cucumber",
        "cup_with_straw",
        "cupcake",
        "curry_rice",
        "custard",
        "cut_of_meat",
        "dango",
        "doughnut",
        "dumpling",
        "ear_of_corn",
        "egg",
        "eggplant",
        "falafel",
        "fish_cake_with_swirl",
        "fork_and_knife",
        "fork_and_knife_with_plate",
        "fortune_cookie",
        "french_fries",
        "fried_shrimp",
        "garlic",
        "glass_of_milk",
        "grapes",
        "green_apple",
        "green_salad",
        "hamburger",
        "honey_pot",
        "hot_beverage",
        "hot_dog",
        "hot_pepper",
        "ice",
        "ice_cream",
        "kitchen_knife",
        "kiwi_fruit",
        "leafy_green",
        "lemon",
        "lobster",
        "lollipop",
        "mango",
        "mate",
        "meat_on_bone",
        "melon",
        "moon_cake",
        "mushroom",
        "oden",
        "onion",
        "oyster",
        "pancakes",
        "peach",
        "peanuts",
        "pear",
        "pie",
        "pineapple",
        "pizza",
        "popcorn",
        "pot_of_food",
        "potato",
        "poultry_leg",
        "pretzel",
        "red_apple",
        "rice_ball",
        "rice_cracker",
        "roasted_sweet_potato",
        "sake",
        "salt",
        "sandwich",
        "shallow_pan_of_food",
        "shaved_ice",
        "shortcake",
        "shrimp",
        "soft_ice_cream",
        "spaghetti",
        "spoon",
        "squid",
        "steaming_bowl",
        "strawberry",
        "stuffed_flatbread",
        "sushi",
        "taco",
        "takeout_box",
        "tangerine",
        "teacup_without_handle",
        "tomato",
        "tropical_drink",
        "tumbler_glass",
        "waffle",
        "watermelon",
        "wine_glass",
    ],
    "gestures": [
        "backhand",
        "fist",
        "gesturing",
        "getting",
        "anatomical_heart",
        "hair",
        "hand",
        "hands",
        "holding",
        "index",
        "ok_hand",
        "playing",
        "pointing",
        "raising",
        "backhand_index_pointing_down",
        "backhand_index_pointing_left",
        "backhand_index_pointing_right",
        "backhand_index_pointing_up",
        "bone",
        "brain",
        "bust_in_silhouette",
        "busts_in_silhouette",
        "call_me_hand",
        "child",
        "clapping_hands",
        "crossed_fingers",
        "ear",
        "ear_with_hearing_aid",
        "eye",
        "eyes",
        "flexed_biceps",
        "folded_hands",
        "foot",
        "footprints",
        "hand_with_fingers_splayed",
        "handshake",
        "index_pointing_up",
        "left-facing_fist",
        "leg",
        "love-you_gesture",
        "mechanical_arm",
        "mechanical_leg",
        "middle_finger",
        "mouth",
        "nail_polish",
        "nose",
        "oncoming_fist",
        "open_hands",
        "palms_up_together",
        "pinching_hand",
        "raised_back_of_hand",
        "raised_fist",
        "raised_hand",
        "raising_hands",
        "right-facing_fist",
        "selfie",
        "sign_of_the_horns",
        "thumbs_down",
        "thumbs_up",
        "tongue",
        "tooth",
        "victory_hand",
        "vulcan_salute",
        "waving_hand",
        "writing_hand",
    ],
    "hearts": ["love", "heart"],
    "smileys": [
        "_face",
        "face_",
        "santa_claus",
        "wheelchair",
        "baby",
        "baby_angel",
        "boy",
        "genie",
        "girl",
        "guard",
        "breast-feeding",
        "worker",
        "couple",
        "detective",
        "elf",
        "fairy",
        "family",
        "horse_racing",
        "kiss",
        "mage",
        "mermaid",
        "merman",
        "merperson",
        "man",
        "men_",
        "police_officer",
        "prince",
        "princess",
        "skier",
        "snowboarder",
        "speaking_head",
        "superhero",
        "supervillain",
        "vampire",
        "woman",
        "women_",
        "zombie",
        "artist",
        "astronaut",
        "cook",
        "factory_worker",
        "farmer",
        "firefighter",
        "health_worker",
        "judge",
        "mechanic",
        "office_worker",
        "person",
        "pilot",
        "scientist",
        "singer",
        "student",
        "teacher",
        "technologist",
        "girl",
        "clause",
        "biking",
        "couple",
        "family",
        "eyes",
        "grinning",
        "heart",
        "kissing",
        "mouth",
        "smiling",
        "sweat",
        "with",
        "alien",
        "alien_monster",
        "anger_symbol",
        "bomb",
        "cat_with_tears_of_joy",
        "cat_with_wry_smile",
        "clown_face",
        "cold_face",
        "collision",
        "confounded_face",
        "confused_face",
        "cowboy_hat_face",
        "crying_cat",
        "crying_face",
        "dashing_away",
        "disappointed_face",
        "dizzy",
        "dizzy_face",
        "downcast_face_with_sweat",
        "drooling_face",
        "exploding_head",
        "expressionless_face",
        "eye_in_speech_bubble",
        "face_blowing_a_kiss",
        "face_savoring_food",
        "face_screaming_in_fear",
        "face_vomiting",
        "face_with_hand_over_mouth",
        "face_with_head-bandage",
        "face_with_medical_mask",
        "face_with_monocle",
        "face_with_open_mouth",
        "face_with_raised_eyebrow",
        "face_with_rolling_eyes",
        "face_with_steam_from_nose",
        "face_with_symbols_on_mouth",
        "face_with_tears_of_joy",
        "face_with_thermometer",
        "face_with_tongue",
        "face_without_mouth",
        "fearful_face",
        "flushed_face",
        "frowning_face",
        "frowning_face_with_open_mouth",
        "ghost",
        "goblin",
        "grimacing_face",
        "grinning_cat",
        "grinning_cat_with_smiling_eyes",
        "grinning_face",
        "grinning_face_with_big_eyes",
        "grinning_face_with_smiling_eyes",
        "grinning_face_with_sweat",
        "grinning_squinting_face",
        "growing_heart",
        "hear-no-evil_monkey",
        "hole",
        "hot_face",
        "hugging_face",
        "hundred_points",
        "hushed_face",
        "kiss_mark",
        "kissing_cat",
        "kissing_face",
        "kissing_face_with_closed_eyes",
        "kissing_face_with_smiling_eyes",
        "left_speech_bubble",
        "loudly_crying_face",
        "love_letter",
        "lying_face",
        "money-mouth_face",
        "nauseated_face",
        "nerd_face",
        "neutral_face",
        "ogre",
        "partying_face",
        "pensive_face",
        "persevering_face",
        "pile_of_poo",
        "pleading_face",
        "pouting_cat",
        "pouting_face",
        "purple_heart",
        "red_heart",
        "relieved_face",
        "revolving_hearts",
        "right_anger_bubble",
        "robot",
        "rolling_on_the_floor_laughing",
        "sad_but_relieved_face",
        "see-no-evil_monkey",
        "shushing_face",
        "skull",
        "skull_and_crossbones",
        "sleeping_face",
        "sleepy_face",
        "slightly_frowning_face",
        "slightly_smiling_face",
        "smiling_cat_with_heart-eyes",
        "smiling_face",
        "smiling_face_with_halo",
        "smiling_face_with_heart-eyes",
        "smiling_face_with_hearts",
        "smiling_face_with_horns",
        "smiling_face_with_smiling_eyes",
        "smiling_face_with_sunglasses",
        "smirking_face",
        "sneezing_face",
        "sparkling_heart",
        "speak-no-evil_monkey",
        "speech_balloon",
        "squinting_face_with_tongue",
        "star-struck",
        "sweat_droplets",
        "thinking_face",
        "thought_balloon",
        "tired_face",
        "two_hearts",
        "unamused_face",
        "upside-down_face",
        "weary_cat",
        "weary_face",
        "white_heart",
        "winking_face",
        "winking_face_with_tongue",
        "woozy_face",
        "worried_face",
        "yawning_face",
        "yellow_heart",
        "zany_face",
        "zipper-mouth_face",
        "zzz",
    ],
    "symbols": [
        "button",
        "sign",
        "aquarius",
        "aries",
        "arrow",
        "black",
        "blue",
        "button",
        "cancer",
        "capricorn",
        "circle",
        "cross",
        "curving",
        "diamond",
        "down",
        "exclamation",
        "fast",
        "gemini",
        "input",
        "symbol",
        "keycap",
        "left",
        "leo",
        "libra",
        "mark",
        "ophiuchus",
        "orange",
        "pisces",
        "pointed",
        "right",
        "sagittarius",
        "scorpio",
        "square",
        "star",
        "taurus",
        "type",
        "virgo",
        "white",
        "antenna_bars",
        "baggage_claim",
        "biohazard",
        "circle",
        "check",
        "children_crossing",
        "cinema",
        "copyright",
        "curly_loop",
        "currency_exchange",
        "customs",
        "diamond_with_a_dot",
        "divide",
        "dotted_six-pointed_star",
        "double_curly_loop",
        "eight-spoked_asterisk",
        "fleur-de-lis",
        "infinity",
        "information",
        "latin",
        "menorah",
        "room",
        "minus",
        "mobile_phone_off",
        "multiply",
        "name_badge",
        "next_track_button",
        "no_bicycles",
        "no_entry",
        "no_littering",
        "no_mobile_phones",
        "no_one_under_eighteen",
        "no_pedestrians",
        "no_smoking",
        "non-potable_water",
        "om",
        "orthodox_cross",
        "passport_control",
        "place_of_worship",
        "plus",
        "potable_water",
        "prohibited",
        "radioactive",
        "registered",
        "sparkle",
        "star_and_crescent",
        "star_of_david",
        "stop_button",
        "trident_emblem",
        "vibration_mode",
        "warning",
        "water_closet",
        "wavy_dash",
        "wheel_of_dharma",
        "yin_yang",
    ],
    "travel": [
        "flag",
        "airplane",
        "behind",
        "clock",
        "cloud",
        "face",
        "globe",
        "light",
        "moon",
        "mountain",
        "oncoming",
        "quarter",
        "railway",
        "rain",
        "statue_of_liberty",
        "tokyo_tower",
        "umbrella",
        "aerial_tramway",
        "airplane",
        "ambulance",
        "anchor",
        "articulated_lorry",
        "auto_rickshaw",
        "automobile",
        "bank",
        "barber_pole",
        "beach",
        "bellhop_bell",
        "bicycle",
        "brick",
        "bridge",
        "building",
        "bus",
        "camping",
        "canoe",
        "carousel_horse",
        "castle",
        "church",
        "circus_tent",
        "city",
        "cloud",
        "comet",
        "compass",
        "construction",
        "convenience_store",
        "cyclone",
        "delivery_truck",
        "department_store",
        "desert",
        "droplet",
        "factory",
        "ferris_wheel",
        "ferry",
        "fire",
        "flying_saucer",
        "fog",
        "foggy",
        "fountain",
        "fuel_pump",
        "globe",
        "helicopter",
        "high_voltage",
        "hindu_temple",
        "horizontal_traffic_light",
        "hospital",
        "hot_springs",
        "hotel",
        "hourglass",
        "house",
        "kaaba",
        "kick_scooter",
        "rail",
        "locomotive",
        "luggage",
        "mantelpiece_clock",
        "map",
        "metro",
        "milky_way",
        "mosque",
        "motor",
        "mount_fuji",
        "mountain",
        "national_park",
        "office_building",
        "oil_drum",
        "oncoming",
        "parachute",
        "passenger_ship",
        "police_car",
        "post_office",
        "racing_car",
        "rainbow",
        "ringed_planet",
        "rocket",
        "roller_coaster",
        "sailboat",
        "satellite",
        "school",
        "seat",
        "shinto_shrine",
        "ship",
        "skateboard",
        "snow-capped_mountain",
        "snowflake",
        "snowman",
        "speedboat",
        "stadium",
        "star",
        "station",
        "stop_sign",
        "stopwatch",
        "sun",
        "suspension_railway",
        "synagogue",
        "taxi",
        "tent",
        "thermometer",
        "-thirty",
        "tornado",
        "tractor",
        "train",
        "tram",
        "umbrella",
        "vehicle",
        "vertical_traffic_light",
        "volcano",
        "watch",
        "water_wave",
        "wedding",
    ],
}


EMOJI_CATEGORIES = {
    "smileys": {
        "label": "Smileys & People",
        "icon": "😀",
        "emojis": [],
    },
    "gestures": {
        "label": "Gestures & Body",
        "icon": "👋",
        "emojis": [],
    },
    "hearts": {
        "label": "Hearts & Love",
        "icon": "❤️",
        "emojis": [],
    },
    "animals_nature": {
        "label": "Animals & Nature",
        "icon": "🐶",
        "emojis": [],
    },
    "food": {
        "label": "Food & Drink",
        "icon": "🍔",
        "emojis": [],
    },
    "activities": {
        "label": "Activities & Sports",
        "icon": "⚽",
        "emojis": [],
    },
    "travel": {
        "label": "Travel & Places",
        "icon": "✈️",
        "emojis": [],
    },
    "objects": {
        "label": "Objects & Tools",
        "icon": "💡",
        "emojis": [],
    },
    "symbols": {
        "label": "Symbols",
        "icon": "✅",
        "emojis": [],
    },
}


class Emoji:
    """
    Simple class to represent an emoji with its name and keywords.
    """

    def __init__(self, emoji_char: str, name: str, keywords: list[str]):
        self.emoji = emoji_char
        self.name = name
        self.keywords = keywords

    def to_dict(self):
        return {
            "emoji": self.emoji,
            "name": self.name,
            "keywords": self.keywords,
        }


def get_emoji_category(emoji: str, alias: list[str]) -> str:
    """
    Determine the category for a given emoji based on its name.
    Uses simple keyword matching against the curated categories.
    """
    emoji_name = emoji.lower()

    for category_key, keywords in CATEGORY_KEYWORDS.items():
        if any(keyword in emoji_name for keyword in keywords) or any(
            keyword in alias for keyword in keywords
        ):
            return category_key

    return "objects"  # Default category if no match found


def get_categorized_emojis() -> dict[str, dict]:
    """
    Return the curated emoji categories:
        ```
            "emoji": "⚽",
            "name": "soccer ball",
            "keywords": ["soccer", "football", "sport"],
        ```
    Keys in dict values are "en" and optionally, "alias". Values of these fields use colons before and after the emoji name, e.g. ":grinning:".
    """
    categories = EMOJI_CATEGORIES.copy()
    for emoji_name, emoji_data in EMOJI_DATA.items():
        if "Israel" in emoji_name:
            continue  # Skip emojis with geopolitical references

        emoji = Emoji(
            emoji_char=emoji_name,
            name=emoji_data["en"].replace(" ", "_").replace(":", ""),
            keywords=[
                kw.replace(" ", "_").replace(":", "")
                for kw in emoji_data.get("alias", [])
            ],
        )
        category = get_emoji_category(emoji_name, emoji.keywords)
        categories[category]["emojis"].append(emoji.to_dict())

    return categories


class EmojiPickerWidget(forms.TextInput):
    """
    A text input with an emoji picker popup for Wagtail admin.
    Uses vanilla JS - no React required.
    """

    template_name = "wagtailadmin/widgets/emoji_picker.html"

    def __init__(self, attrs=None):
        default_attrs = {"class": "emoji-picker-input", "readonly": "readonly"}
        if attrs:
            default_attrs.update(attrs)
        super().__init__(attrs=default_attrs)

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        context["emoji_categories"] = get_categorized_emojis()
        context["emoji_categories_json"] = mark_safe(
            json.dumps(get_categorized_emojis())
        )
        return context

    class Media:
        css = {"all": ("css/emoji_picker.css",)}
        js = ("js/emoji_picker.js",)


# Default colors for ColorPickerWidget when WebDesignSettings is not available
DEFAULT_COLOR_MAP = {
    "transparent": "transparent",
    "white": "hsl(0, 0%, 100%)",
    "black": "hsl(0, 100%, 0.78%)",
    "safeLightAccent": "hsl(342.63, 80.85%, 81.57%)",
    "safeDarkAccent": "hsl(0, 0%, 0%)",
    "safeInverseAccent": "hsl(0, 0%, 0%)",
    "safeInverseLightAccent": "hsl(0, 0%, 0%)",
    "safeInverseDarkAccent": "hsl(0, 0%, 100%)",
    "accent": "hsl(342.63, 80.85%, 81.57%)",
    "lightAccent": "hsl(343.29, 95.89%, 71.37%)",
    "darkAccent": "hsl(342.11, 40.43%, 27.65%)",
}

DEFAULT_COLOR_CHOICES = [
    ("transparent", "Transparent"),
    ("white", "White"),
    ("black", "Black"),
    ("safeLightAccent", "Safe Light Accent"),
    ("safeDarkAccent", "Safe Dark Accent"),
    ("safeInverseAccent", "Safe Inverse Accent"),
    ("safeInverseLightAccent", "Safe Inverse Light Accent"),
    ("safeInverseDarkAccent", "Safe Inverse Dark Accent"),
    ("accent", "Accent"),
    ("lightAccent", "Light Accent"),
    ("darkAccent", "Dark Accent"),
]


class ColorPickerWidget(forms.TextInput):
    """
    A text input with a color picker popup for Wagtail admin.
    Uses colors from WebDesignSettings with custom color support.
    Uses vanilla JS - no React required.
    """

    template_name = "wagtailadmin/widgets/color_picker.html"

    def __init__(self, attrs=None):
        default_attrs = {"class": "color-picker-input"}
        if attrs:
            default_attrs.update(attrs)
        super().__init__(attrs=default_attrs)

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)

        # Try to get colors from WebDesignSettings
        color_choices = []
        color_map = DEFAULT_COLOR_MAP.copy()

        try:
            from wagtail.models import Site

            from apps.core.models import WebDesignSettings

            site = Site.objects.filter(is_default_site=True).first()
            if site:
                settings = WebDesignSettings.load(request_or_site=site)
                if settings:
                    color_choices = settings.get_color_choices()
                    color_map = settings.get_color_map()
        except Exception:
            pass

        # Fallback to defaults if no settings found
        if not color_choices:
            color_choices = DEFAULT_COLOR_CHOICES

        # Add color values to choices for template
        # Format: (value_key, label, actual_color_value)
        enriched_choices = []
        for choice in color_choices:
            if len(choice) >= 2:
                key = choice[0]
                label = choice[1]
                color_value = color_map.get(key, key)
                enriched_choices.append((key, label, color_value))

        context["widget"]["color_choices"] = enriched_choices
        context["widget"]["color_map_json"] = mark_safe(json.dumps(color_map))

        return context

    class Media:
        css = {"all": ("css/color_picker.css",)}
        js = ("js/color_picker.js",)
