collections:
  - name: community.general
    version: "13.5.0"
    source: https://galaxy.ansible.com
  - name: community.crypto
    version: "3.5.0"
    source: https://galaxy.ansible.com
  - name: community.docker
    version: "5.4.0"
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: "2.2.2"
    source: https://galaxy.ansible.com
