# Generated by Django 6.0.8 on 2026-10-05 19:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import modelsearch.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Full name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('accepted_tos', models.BooleanField(default=False, help_text='Whether the user has accepted the terms of service.', verbose_name='Accepted Terms of Service')),
                ('staff_state', django_fsm.FSMField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('suspended', 'Suspended')], default='inactive', max_length=50, protected=True, verbose_name='Staff state')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            bases=(modelsearch.index.Indexed, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('profile_picture_url', models.URLField(blank=True, help_text='Uploaded via getpronto. Set by the upload flow.', verbose_name='Profile picture URL')),
                ('profile_picture_getpronto_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Getpronto file ID')),
                ('access_needs', models.TextField(blank=True, help_text='Free-text access needs shared with peers when booking.', verbose_name='Access needs')),
                ('access_needs_visible_to_peer', models.BooleanField(default=True, help_text='Whether a peer may see your access needs ahead of a meeting.', verbose_name='Share access needs with peer')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members', 'Members only'), ('private', 'Private')], default='members', max_length=10, verbose_name='Visibility')),
                ('notify_meeting_request', models.BooleanField(default=True, verbose_name='Meeting request alerts')),
                ('notify_meeting_approved', models.BooleanField(default=True, verbose_name='Meeting approved alerts')),
                ('notify_meeting_reminder', models.BooleanField(default=True, verbose_name='Meeting reminder alerts')),
                ('notify_review_received', models.BooleanField(default=True, verbose_name='Review received alerts')),
                ('notify_refund_request', models.BooleanField(default=True, verbose_name='Refund request alerts')),
                ('notify_peer_application_update', models.BooleanField(default=True, verbose_name='Peer application update alerts')),
                ('notify_platform_announcements', models.BooleanField(default=True, verbose_name='Platform announcements')),
                ('country', models.CharField(blank=True, default='GB', help_text='ISO 3166-1 alpha-2 country code (used for Stripe Connect).', max_length=2, verbose_name='Country')),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=50, verbose_name='Timezone')),
                ('languages', models.ManyToManyField(blank=True, related_name='user_profiles', to='taxonomy.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
